
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:null};
const val=id=>$(id)?.value||"";
const DAY=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const blocks=[
 ["Re-entry",1,4,"Up to 2 short run/walk sessions each week","No weighted-pack walking yet","Rebuild routine, aerobic fitness and basic tissue tolerance."],
 ["Foundation I",5,8,"2 runs each week · about 3–6 miles","2–4 miles easy with a light pack","Build continuous running tolerance and introduce loaded walking."],
 ["Foundation II",9,12,"2–3 runs each week · about 6–10 miles","3–5 miles easy","Build the aerobic base, bodyweight strength and loaded-carry durability."],
 ["Build I",13,16,"3 runs each week · about 10–16 miles","4–6 miles","Introduce controlled faster running while increasing loaded walking."],
 ["Build II",17,20,"3 runs each week · about 14–20 miles","5–8 miles","Grow the long run and weighted-pack walking while maintaining strength."],
 ["Build III",21,24,"3 runs each week · about 16–22 miles","6–10 miles","Consolidate the build and test aerobic/bodyweight progress."],
 ["Specificity I",25,28,"3–4 runs each week · about 20–26 miles","8–10 miles","Improve running economy, weighted-pack walking technique and carries."],
 ["Specificity II",29,32,"3–4 runs each week · about 22–30 miles","8–12 miles","Combine faster running with long aerobic work and loaded movement."],
 ["Specificity III",33,36,"4 runs each week · about 26–34 miles","10–14 miles","Build consecutive-day durability while maintaining strength."],
 ["Specificity IV",37,40,"3–4 runs each week · about 24–32 miles","10–14 miles","Absorb accumulated work and test durability."],
 ["Work Capacity I",41,44,"4 runs each week · about 28–38 miles","12–16 miles","Build large accumulated workload and time on feet."],
 ["Work Capacity II",45,48,"4–5 runs each week · about 34–45 miles","14–20 miles","Peak specificity and consecutive-day work."],
 ["Peak / Consolidate",49,52,"About 38–50 miles only if earned","16–24 miles only if earned","Assess peak work capacity without forcing arbitrary mileage."],
 ["Taper",53,56,"Reduce volume progressively","Reduce, then eliminate","Dissipate fatigue while retaining selected intensity."]
];
const templates={
 "Re-entry":["Recovery & mobility","Full-body strength — Session A","Easy aerobic row","Full-body strength — Session B","Easy aerobic row","Introductory run/walk","Easy row + trunk work"],
 "Foundation I":["Recovery & mobility","Full-body strength + bodyweight training","Easy aerobic row","Easy run + lower-leg durability","Full-body strength — Session B","Long easy run or light weighted-pack walk","Easy recovery row"],
 "Foundation II":["Recovery & mobility","Full-body strength + bodyweight training","Easy aerobic row","Easy run + lower-leg durability","Full-body strength — Session B","Long easy run or light weighted-pack walk","Easy recovery row"],
 "Build I":["Recovery & mobility","Quality run + strength","Easy run","Rowing threshold work","Strength + bodyweight training","Long run or weighted-pack walk","Easy recovery row"],
 "Build II":["Recovery & mobility","Quality run + strength","Easy run","Easy aerobic row","Strength + bodyweight training","Long run or weighted-pack walk","Easy recovery row"],
 "Build III":["Recovery & mobility","Quality run","Easy run + strength","Easy aerobic row","Strength + bodyweight training","Long run or weighted-pack walk","Easy recovery row"],
 "Specificity I":["Recovery & mobility","Quality run + bodyweight training","Easy run","Strength + easy row","Easy run + loaded carries","Long weighted-pack walk or run","Recovery aerobic work"],
 "Specificity II":["Recovery & mobility","Quality run + bodyweight training","Easy run","Strength + easy row","Easy run + loaded carries","Long weighted-pack walk or run","Recovery aerobic work"],
 "Specificity III":["Recovery & mobility","Quality run","Easy run","Strength + loaded carries","Easy run","Long weighted-pack walk or run","Recovery aerobic work"],
 "Specificity IV":["Recovery & mobility","Quality run","Easy run","Strength + easy row","Easy run","Long weighted-pack walk or run","Recovery aerobic work"],
 "Work Capacity I":["Recovery & mobility","Quality run","Medium aerobic run","Strength + loaded carries","Easy run","Long weighted-pack walk or run","Easy aerobic work while fatigued"],
 "Work Capacity II":["Recovery & mobility","Quality run","Medium aerobic run","Strength + loaded carries","Easy run","Long weighted-pack walk or run","Easy aerobic work while fatigued"],
 "Peak / Consolidate":["Recovery & mobility","Specific hard session","Medium aerobic run","Carries + strength maintenance","Easy run","Peak specific session","Recovery aerobic work"],
 "Taper":["Recovery & mobility","Short quality session","Easy aerobic work","Light strength","Easy aerobic work","Short specific session","Recovery"]
};
const ex=(name,dose,rest,cue,type)=>({name,dose,rest,cue,type:type||"Strength"});
const A=[ex("Back squat","3 × 5","2–3 min","Keep the whole foot planted and finish each rep tall."),ex("Romanian deadlift","3 × 6–8","2–3 min","Push the hips back while keeping the spine neutral."),ex("Overhead press","3 × 5","2 min","Brace the trunk and press without leaning backward."),ex("Pull-ups","3–5 submaximal sets","2 min","Stop before form breaks. Use a resistance band if needed.","Bodyweight"),ex("Tibialis raises","3 × 15–25","60–90 sec","Lift the forefoot toward the shin through a controlled range.","Durability"),ex("Calf / soleus raises","3 × 12–20","60–90 sec","Use straight-knee and bent-knee variations across the week.","Durability"),ex("Neck harness","2–3 sets each direction","60 sec","Use light load and smooth motion. Never jerk the neck.","Durability"),ex("Grip work","2–3 sets","60–90 sec","Use hangs, carries or grip tools without max testing.","Durability")];
const B=[ex("Split squat or reverse lunge","3 × 6–8 each leg","2 min","Stay balanced and keep the front foot planted."),ex("Hip hinge","3 × 6–8","2–3 min","Use a deadlift or dumbbell hinge with a neutral spine."),ex("Press + row","3 × 6–10 each","90–120 sec","Pair a horizontal press with a controlled row."),ex("Suitcase carry","3 × 40–100 m each side","As needed","Walk tall without leaning toward the weight.","Carry"),ex("Tibialis + soleus","3 sets each","60–90 sec","Control the full range rather than bouncing.","Durability"),ex("Neck harness","2–3 controlled sets","60 sec","Keep the load modest.","Durability"),ex("Forearm roller","2–3 climbs","60–90 sec","Use smooth wrist flexion and extension.","Durability")];
const definitions={readiness:"A daily signal built from recovery, pain/movement and fueling information. It changes training stress; it is not a medical diagnosis.",HRV:"Heart-rate variability is the beat-to-beat variation in time between heartbeats. The app compares your value with your own history.","resting heart rate":"Your heart rate when rested, ideally measured under similar morning conditions.","grip strength":"A standardized grip measurement used as one small neuromuscular readiness signal.","session effort":"Your overall rating of how hard the session felt: 1 is extremely easy and 10 is maximal.",threshold:"A hard but controlled intensity that can be sustained for meaningful work.","RKC plank":"A high-tension forearm plank: squeeze glutes, quads and abs hard while holding a straight body line."};
function mondayDate(src){const d=new Date(src||Date.now()),i=(d.getDay()+6)%7;d.setHours(12,0,0,0);d.setDate(d.getDate()-i);return d}
function programStart(){return localStorage.programStart?new Date(localStorage.programStart):new Date()}
function currentWeek(){if(!localStorage.programStart)return 1;const start=new Date(localStorage.programStart),now=new Date();start.setHours(12,0,0,0);now.setHours(12,0,0,0);return Math.max(1,Math.min(56,Math.floor((now-start)/604800000)+1))}
let viewedWeek=currentWeek();
function blockForWeek(w){const b=blocks.find(x=>w>=x[1]&&w<=x[2])||blocks[0];return{name:b[0],start:b[1],end:b[2],run:b[3],ruck:b[4],focus:b[5]}}
function daysFor(b){return templates[b.name]||templates["Re-entry"]}
function dayIndex(){return(new Date().getDay()+6)%7}
function sessionName(){const b=blockForWeek(currentWeek());return daysFor(b)[dayIndex()]}
function makeSession(name){
 const row=mins=>[ex("Warm-up",mins,"—","Start easy and build gradually.","Warm-up")];
 if(name==="Full-body strength — Session A")return{title:name,type:"Full Body",duration:"55–75 min",effort:"Moderate",why:"Build fundamental strength for running, loaded walking, posture and injury resistance.",steps:A};
 if(name==="Full-body strength — Session B")return{title:name,type:"Full Body",duration:"55–75 min",effort:"Moderate",why:"Build unilateral leg strength, trunk stability and loaded-carry durability.",steps:B};
 if(name.includes("Quality run + bodyweight"))return{title:name,type:"Run + Bodyweight",duration:"60–85 min",effort:"Hard / controlled",why:"Develop faster running while maintaining strict push-up and pull-up capacity.",steps:[ex("Quality run","Use quality-run structure","—","Complete the faster running first.","Run"),ex("Push-ups","4–6 submaximal sets","2 min","Strict reps; stop before failure.","Bodyweight"),ex("Pull-ups","4–6 submaximal sets","2 min","Strict or assisted.","Bodyweight"),ex("RKC plank","3 × 20–40 sec","60 sec","Squeeze glutes, quads and abs hard.","Core")]}; if(name.includes("Easy run + loaded carries"))return{title:name,type:"Run + Carry",duration:"60–90 min",effort:"Moderate",why:"Combine running durability with posture and awkward-load capacity.",steps:[ex("Easy run","Use current phase target","Continuous","Conversational pace.","Run"),ex("Bear-hug sandbag carry","3–5 rounds","As needed","Use a manageable load.","Carry"),ex("Suitcase carry","3 rounds each side","As needed","Stay tall without leaning.","Carry")]}; if(name.includes("bodyweight training"))return{title:name,type:"Full Body",duration:"60–80 min",effort:"Moderate",why:"Maintain strength while improving strict push-up and pull-up capacity.",steps:[...A.slice(0,4),ex("Push-ups","4–6 submaximal sets","2 min","Leave 2–4 clean reps in reserve.","Bodyweight"),ex("RKC plank","3 × 20–40 sec","60 sec","Squeeze glutes, quads and abs hard; keep a straight line.","Core")]};
 if(name.includes("Strength + loaded carries")||name.includes("Carries + strength"))return{title:name,type:"Strength + Carry",duration:"60–85 min",effort:"Moderate",why:"Maintain force production and train posture under external load.",steps:[...B.slice(0,3),ex("Sandbag bear-hug carry","3–5 rounds","As needed","Walk under control.","Carry"),ex("Suitcase carry","3 rounds each side","As needed","Stay tall without leaning.","Carry")]};
 if(name.includes("Strength + easy row"))return{title:name,type:"Strength + Aerobic",duration:"70–100 min",effort:"Moderate",why:"Maintain strength and add low-impact aerobic volume.",steps:[...B.slice(0,4),ex("Easy row","30–45 min","Continuous","Keep a conversational effort.","Row")]};
 if(name.includes("strength")&&name.includes("run"))return{title:name,type:"Run + Strength",duration:"70–100 min",effort:"Moderate / hard",why:"Develop running while preserving strength.",steps:[...row("15 min"),ex("Controlled quality run","20–30 min total","Variable","Hard but controlled; never all-out.","Run"),...A.slice(0,3)]};
 if(name.includes("Easy aerobic row"))return{title:name,type:"Aerobic",duration:"50–90 min",effort:"Easy",why:"Build the aerobic engine with minimal impact.",steps:[ex("Warm-up row","5–10 min","—","Very easy rowing.","Row"),ex("Main aerobic row","40–75 min","Continuous","Conversational effort.","Row"),ex("Cool-down row","5 min","—","Very easy.","Row")]};
 if(name.includes("recovery row")||name.includes("Recovery aerobic"))return{title:name,type:"Recovery",duration:"25–60 min",effort:"Very easy",why:"Support recovery while preserving aerobic rhythm.",steps:[ex("Easy row or walk","25–60 min","Continuous","Finish feeling better than you started.","Aerobic")]};
 if(name.includes("row")&&name.includes("trunk"))return{title:name,type:"Aerobic + Core",duration:"45–70 min",effort:"Easy",why:"Build aerobic capacity and trunk stiffness.",steps:[ex("Easy row","30–60 min","Continuous","Conversational effort.","Row"),ex("RKC plank","3 × 20–40 sec","60 sec","Squeeze glutes, quads and abs hard.","Core"),ex("Suitcase carry","3 rounds each side","As needed","Stay tall and breathe under control.","Carry")]};
 if(name.includes("Rowing threshold"))return{title:name,type:"Aerobic",duration:"35–60 min",effort:"Moderate / hard",why:"Develop higher aerobic power with low mechanical cost.",steps:[ex("Warm-up row","10 min","—","Easy.","Row"),ex("Controlled threshold work","20–40 min total","Variable","Hard but controlled; do not force a universal number.","Row"),ex("Cool-down row","5–10 min","—","Easy.","Row")]};
 if(name.includes("Recovery & mobility"))return{title:name,type:"Recovery",duration:"25–45 min",effort:"Very easy",why:"Reduce fatigue while keeping the body moving and joints comfortable.",steps:[ex("Easy walk or row","20–30 min","Continuous","Very easy.","Aerobic"),ex("Ankle mobility","2 × 8–10 each side","—","Move through pain-free range.","Mobility"),ex("Hip mobility","5–10 min","—","Gentle controlled movement.","Mobility"),ex("Light trunk work","2–3 easy sets","60 sec","Plank, side plank or dead bug.","Core")]};
 if(name.includes("Introductory run/walk"))return{title:name,type:"Run",duration:"20–40 min",effort:"Easy",why:"Reintroduce running-specific bone, tendon and foot stress without unnecessary overload.",steps:[ex("Warm-up walk","5–10 min","—","Brisk but comfortable.","Run"),ex("Run / walk","10–25 min total","Alternate as needed","Keep it easy. Stop for focal pain or altered gait.","Run"),ex("Cool-down walk","5 min","—","Easy.","Run")]};
 if(name.includes("lower-leg durability"))return{title:name,type:"Run + Durability",duration:"45–70 min",effort:"Easy",why:"Pair controlled running with targeted shin, calf and ankle strengthening.",steps:[ex("Easy run","Use current phase target","Continuous","Conversational pace.","Run"),ex("Tibialis raises","3 × 20","60 sec","Control the movement.","Durability"),ex("Seated soleus raises","3 × 15–20","60–90 sec","Use moderate load.","Durability"),ex("Eccentric calf raises","3 × 12–15","60–90 sec","Lower slowly.","Durability")]};
 if(name.includes("Quality run"))return{title:name,type:"Run",duration:"45–75 min",effort:"Hard / controlled",why:"Improve sustainable speed after aerobic and tissue tolerance are established.",steps:[ex("Warm-up","15–20 min","—","Easy jog plus relaxed strides.","Run"),ex("Main quality work","Phase-specific intervals or tempo","Variable","Use individual pace, heart-rate and lactate data.","Run"),ex("Cool-down","10–15 min","—","Easy jog.","Run")]};
 if(name.includes("Medium aerobic run"))return{title:name,type:"Run",duration:"45–75 min",effort:"Easy / moderate",why:"Accumulate meaningful running volume between easy and long sessions.",steps:[ex("Medium run","Use weekly allocation","Continuous","Stay below threshold and finish controlled.","Run")]};
 if(name.includes("Easy run"))return{title:name,type:"Run",duration:"Varies",effort:"Easy",why:"Build running-specific aerobic fitness and tissue tolerance.",steps:[ex("Warm-up","5–10 min","—","Walk or jog easily.","Run"),ex("Main run","Use this week’s mileage allocation","Continuous","Conversational pace; do not chase speed.","Run"),ex("Cool-down","5–10 min","—","Easy jog or walk.","Run")]};
 if(name.includes("Long"))return{title:name,type:"Endurance",duration:"Long",effort:"Easy / moderate",why:"Build time-on-feet and loaded-movement durability.",steps:[ex("Long session","Use current weekly target","Continuous","Increase distance before pack load; keep gait normal.","Endurance")]};
 if(name.includes("Light strength"))return{title:name,type:"Strength",duration:"35–50 min",effort:"Easy",why:"Retain movement quality during taper without creating soreness.",steps:[ex("Squat","2 × 5","2 min","Use about 60–70% of normal training load."),ex("Hinge","2 × 6","2 min","Easy to moderate."),ex("Press","2 × 5","90 sec","Easy."),ex("Pull-ups","2–3 easy sets","90 sec","No failure.","Bodyweight")]};
 return{title:name,type:"Specific",duration:"30–60 min",effort:"Controlled",why:"Complete the current phase-specific session with clean technique and adaptive restraint.",steps:[ex("Main session","Follow current block target","—","Stop for focal pain, altered gait or red recovery flags.","Specific")]};
}
function logs(){return JSON.parse(localStorage.trainingLogs||"[]")}function workouts(){return JSON.parse(localStorage.workoutHistory||"[]")}
function todayKey(){return new Date().toDateString()}function todayCheckin(){return logs().find(x=>new Date(x.date).toDateString()===todayKey())}function todayWorkout(){return workouts().find(x=>new Date(x.date).toDateString()===todayKey()&&x.completed==="YES")}
function taskDone(k){return localStorage.getItem("task_"+k+"_"+todayKey())==="1"}function setTask(k,v){localStorage.setItem("task_"+k+"_"+todayKey(),v?"1":"0")}
function systemic(){const sl=num("sleep"),q=num("sleepQ"),f=num("fatigue"),h=num("hrv"),hb=num("hrvBase"),r=num("rhr"),rb=num("rhrBase"),g=num("grip"),gb=num("gripBase"),p=val("performance");if([sl,q,f,h,r].every(x=>x===null)&&!p)return"";if((sl!==null&&sl<6)||(q!==null&&q<=2)||(f!==null&&f>=4)||(hb&&h!==null&&h<.85*hb)||(rb&&r!==null&&r>rb+8)||p==="NO")return"RED";if((sl!==null&&sl<7)||q===3||f===3||(hb&&h!==null&&h<.92*hb)||(rb&&r!==null&&r>rb+5)||(gb&&g!==null&&g<.9*gb))return"YELLOW";return"GREEN"}
function mechanical(){const p=num("pain");if(p===null&&!$("focal").checked&&!$("gait").checked)return"";if($("focal").checked||$("gait").checked||(p!==null&&p>=5))return"RED";if(p!==null&&p>=3)return"YELLOW";return"GREEN"}
function fueling(){const w=num("weight"),a=num("weightAvg"),l=num("load");if(w===null||a===null||l===null)return"";if(w<a*.985&&l>=7)return"RED";if(w<a*.99&&l>=5)return"YELLOW";return"GREEN"}
function decision(){const a=systemic(),b=mechanical(),c=fueling(),o=!a&&!b&&!c?"":(a==="RED"||b==="RED"?"RED":(a==="YELLOW"||b==="YELLOW"||c==="RED"?"YELLOW":"GREEN"));let score=92;if(a==="YELLOW")score-=18;if(a==="RED")score-=42;if(b==="YELLOW")score-=18;if(b==="RED")score-=55;if(c==="YELLOW")score-=8;if(c==="RED")score-=16;score=Math.max(15,Math.min(98,score));let run="Full phase plan",ruck="Full phase plan",row="Phase plan",strength="Full plan",intensity="Planned",nutrition="Follow phase target",warning="";if(!o)return{a,b,c,o,score:0,run:"Complete check-in",ruck:"Complete check-in",row:"Complete check-in",strength:"Complete check-in",intensity:"Complete check-in",nutrition:"Complete check-in",warning:""};if(b==="RED"){run="No running";ruck="No weighted-pack walking";row="Easy row if pain-free";strength="Non-aggravating only";intensity="No hard training";warning="Mechanical override: favorable recovery metrics do not justify impact or loaded walking."}else if(o==="RED"){run="Row or walk only";ruck="No loaded walking";row="Recovery row";strength="Reduce about 50%";intensity="No hard training"}else if(o==="YELLOW"){run="Reduce about 25–40%; keep easy";ruck="Reduce distance/load";row="Prefer easy rowing";strength="Reduce about 30%";intensity="No hard intervals"}if(c==="RED")nutrition="Add energy/carbohydrate; review deficit";else if(c==="YELLOW")nutrition="Hold intake; add carbohydrate around training";return{a,b,c,o,score,run,ruck,row,strength,intensity,nutrition,warning}}
function dayKey(d){return new Date(d).toDateString()}
function missedDays(){if(!localStorage.programStart)return[];const start=new Date(localStorage.programStart),end=new Date();start.setHours(12,0,0,0);end.setHours(12,0,0,0);end.setDate(end.getDate()-1);const resolved=new Set(logs().map(x=>dayKey(x.date))),failed=new Set(JSON.parse(localStorage.failedDays||"[]")),out=[];for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const k=d.toDateString();if(!resolved.has(k)&&!failed.has(k))out.push(new Date(d))}return out}
function markMissedDay(d){const arr=JSON.parse(localStorage.failedDays||"[]"),k=dayKey(d);if(!arr.includes(k))arr.push(k);localStorage.failedDays=JSON.stringify(arr);renderAll()}
function renderMissedBanner(){const m=missedDays(),b=$("missedDayBanner");if(!b)return;if(!m.length){b.classList.add("hidden");b.innerHTML="";return}const d=m[0];b.classList.remove("hidden");b.innerHTML='<div class="missed-icon">!</div><div><small>CURRICULUM DEBT</small><strong>Missed check-in · '+d.toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"})+'</strong><p>Resolve this day before it can count toward phase mastery.</p><div class="missed-actions"><button id="failMissed">Mark missed</button></div></div>';$("failMissed").onclick=()=>markMissedDay(d)}
function requiredFields(){const ids=["hrv","rhr","sleep","sleepQ","fatigue","load","pain","performance","weight"];let done=0;ids.forEach(id=>{const el=$(id),ok=String(el.value).trim()!=="";done+=ok?1:0;el.closest(".field").classList.toggle("field-done",ok);el.closest(".field").classList.toggle("field-needed",!ok)});const left=ids.length-done,b=$("checkinProgress");if(left===0){b.classList.add("complete");b.querySelector(".attention-icon").textContent="✓";b.querySelector("strong").textContent="Ready to evaluate";$("checkinProgressText").textContent="Required fields complete."}else{b.classList.remove("complete");b.querySelector(".attention-icon").textContent="!";b.querySelector("strong").textContent="Needs attention";$("checkinProgressText").textContent=left+" required field"+(left===1?"":"s")+" remaining."}}
function avg(a){const x=a.filter(Number.isFinite);return x.length?x.reduce((p,c)=>p+c,0)/x.length:null}
function applyBaselines(){const l=logs(),hb=avg(l.slice(0,28).map(x=>x.hrv)),rb=avg(l.slice(0,28).map(x=>x.rhr)),gb=avg(l.slice(0,28).map(x=>x.grip)),wa=avg(l.slice(0,7).map(x=>x.weight));if(hb!==null)$("hrvBase").value=hb.toFixed(0);if(rb!==null)$("rhrBase").value=rb.toFixed(0);if(gb!==null)$("gripBase").value=gb.toFixed(1);if(wa!==null)$("weightAvg").value=wa.toFixed(1)}
function persistInputs(){["hrv","hrvBase","rhr","rhrBase","sleep","sleepQ","fatigue","grip","gripBase","load","pain","performance","weight","weightAvg"].forEach(id=>localStorage.setItem("input_"+id,$(id).value));localStorage.input_focal=$("focal").checked?"1":"0";localStorage.input_gait=$("gait").checked?"1":"0"}
function evaluate(){const d=decision();[["sysStatus",d.a],["mechStatus",d.b],["fuelStatus",d.c]].forEach(x=>{$(x[0]).textContent=x[1]||"—";$(x[0]).style.color=x[1]==="GREEN"?"var(--green)":x[1]==="YELLOW"?"var(--yellow)":x[1]==="RED"?"var(--red)":""});[["runDecision",d.run],["ruckDecision",d.ruck],["c2Decision",d.row],["strengthDecision",d.strength],["intensityDecision",d.intensity],["nutritionDecision",d.nutrition]].forEach(x=>$(x[0]).textContent=x[1]);$("warningBox").textContent=d.warning;$("warningBox").classList.toggle("hidden",!d.warning);$("results").classList.remove("hidden");persistInputs()}
function saveCheckin(){evaluate();const d=decision();if(!d.o)return;if(!localStorage.programStart)localStorage.programStart=new Date().toISOString();const l=logs();l.unshift({date:new Date().toISOString(),week:currentWeek(),weight:num("weight"),hrv:num("hrv"),rhr:num("rhr"),grip:num("grip"),sleep:num("sleep"),overall:d.o,score:d.score});localStorage.trainingLogs=JSON.stringify(l.slice(0,365));dbSet("trainingLogs",localStorage.trainingLogs);setTask("checkin",true);closeCheckin();renderAll()}
function saveWorkout(c){const arr=workouts(),name=sessionName();arr.unshift({date:new Date().toISOString(),week:currentWeek(),session:name,rpe:num("sessionRPE"),duration:num("sessionDuration"),postPain:num("postPain"),completed:c||"YES",note:val("sessionNote")});localStorage.workoutHistory=JSON.stringify(arr.slice(0,500));dbSet("workoutHistory",localStorage.workoutHistory);setTask("workout",true);$("completionBanner").classList.remove("hidden");setTimeout(()=>$("completionBanner").classList.add("hidden"),1600);renderAll()}
function svg(name){const low=name.toLowerCase(),pl=low.includes("plank"),sq=low.includes("squat")||low.includes("lunge"),hi=low.includes("deadlift")||low.includes("hinge"),pu=low.includes("pull-up")||low.includes("pull up"),pr=low.includes("press");let body='<circle cx="160" cy="55" r="16" fill="#9ed9ff"/><line x1="160" y1="72" x2="160" y2="130" stroke="#9ed9ff" stroke-width="8"/><line x1="160" y1="88" x2="120" y2="112" stroke="#9ed9ff" stroke-width="7"/><line x1="160" y1="88" x2="200" y2="112" stroke="#9ed9ff" stroke-width="7"/><line x1="160" y1="130" x2="130" y2="185" stroke="#9ed9ff" stroke-width="8"/><line x1="160" y1="130" x2="190" y2="185" stroke="#9ed9ff" stroke-width="8"/>';if(pl)body='<circle cx="75" cy="100" r="15" fill="#9ed9ff"/><line x1="92" y1="108" x2="205" y2="125" stroke="#9ed9ff" stroke-width="9"/><line x1="110" y1="112" x2="95" y2="155" stroke="#9ed9ff" stroke-width="7"/><line x1="205" y1="125" x2="260" y2="145" stroke="#9ed9ff" stroke-width="8"/>';if(sq)body='<circle cx="160" cy="55" r="16" fill="#9ed9ff"/><line x1="160" y1="72" x2="160" y2="128" stroke="#9ed9ff" stroke-width="8"/><line x1="160" y1="128" x2="120" y2="165" stroke="#9ed9ff" stroke-width="8"/><line x1="120" y1="165" x2="95" y2="205" stroke="#9ed9ff" stroke-width="8"/><line x1="160" y1="128" x2="200" y2="165" stroke="#9ed9ff" stroke-width="8"/><line x1="200" y1="165" x2="225" y2="205" stroke="#9ed9ff" stroke-width="8"/><line x1="95" y1="90" x2="225" y2="90" stroke="#eef7ff" stroke-width="5"/>';if(hi)body='<circle cx="120" cy="65" r="16" fill="#9ed9ff"/><line x1="135" y1="78" x2="205" y2="116" stroke="#9ed9ff" stroke-width="9"/><line x1="202" y1="116" x2="200" y2="190" stroke="#9ed9ff" stroke-width="8"/><line x1="205" y1="116" x2="238" y2="185" stroke="#9ed9ff" stroke-width="8"/><line x1="130" y1="170" x2="205" y2="170" stroke="#eef7ff" stroke-width="5"/>';if(pu)body='<line x1="75" y1="35" x2="245" y2="35" stroke="#eef7ff" stroke-width="5"/><circle cx="160" cy="90" r="16" fill="#9ed9ff"/><line x1="160" y1="106" x2="160" y2="165" stroke="#9ed9ff" stroke-width="8"/><line x1="160" y1="115" x2="115" y2="35" stroke="#9ed9ff" stroke-width="7"/><line x1="160" y1="115" x2="205" y2="35" stroke="#9ed9ff" stroke-width="7"/><line x1="160" y1="165" x2="135" y2="215" stroke="#9ed9ff" stroke-width="8"/>';if(pr)body+='<line x1="100" y1="32" x2="220" y2="32" stroke="#eef7ff" stroke-width="5"/>';return'<svg viewBox="0 0 320 240"><line x1="45" y1="215" x2="275" y2="215" stroke="#35526b" stroke-width="3"/>'+body+'</svg>'}
function openInfo(t){$("modalTitle").textContent=t.charAt(0).toUpperCase()+t.slice(1);$("modalContent").innerHTML='<div class="modal-copy"><p>'+(definitions[t]||"Defined by the current session context.")+'</p></div>';$("infoModal").classList.remove("hidden")}
function openExercise(e){$("modalTitle").textContent=e.name;$("modalContent").innerHTML='<div class="exercise-visual">'+svg(e.name)+'</div><div class="modal-stats"><div><span>WORK</span><strong>'+e.dose+'</strong></div><div><span>REST</span><strong>'+e.rest+'</strong></div><div><span>TYPE</span><strong>'+e.type+'</strong></div></div><div class="modal-copy"><h3>How to perform it</h3><p>'+e.cue+'</p><h3>Key rule</h3><p>Use controlled technique and stop if pain changes your movement pattern.</p></div>';$("infoModal").classList.remove("hidden")}
function closeModal(){$("infoModal").classList.add("hidden")}function bindInfo(root){(root||document).querySelectorAll(".info-dot[data-term]").forEach(b=>b.onclick=e=>{e.stopPropagation();openInfo(b.dataset.term)})}
function renderToday(){const d=todayCheckin(),det=makeSession(sessionName()),done=todayWorkout();$("todayDate").textContent=new Date().toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"});$("todayWorkoutName").textContent=det.title;$("todayWorkoutType").textContent=det.type.toUpperCase();$("todayWorkoutMeta").textContent=det.duration+" · "+det.effort;$("taskWorkoutSub").textContent=done?"Completed today":"Follow the adaptive prescription";const score=d?.score||0;$("readinessScore").textContent=d?score:"—";$("scoreRing").style.setProperty("--score",score);$("scoreRing").style.setProperty("--ring",d?(d.overall==="GREEN"?"var(--green)":d.overall==="YELLOW"?"var(--yellow)":"var(--red)"):"var(--green)");$("readinessLabel").textContent=d?(d.overall==="GREEN"?"Good":d.overall==="YELLOW"?"Caution":"Recover"):"Check in";$("readinessLabel").style.color=d?(d.overall==="GREEN"?"var(--green)":d.overall==="YELLOW"?"var(--yellow)":"var(--red)"):"";$("readinessMessage").textContent=d?(d.overall==="GREEN"?"You’re ready for the planned session.":d.overall==="YELLOW"?"Train, but reduce today’s stress.":"Recovery takes priority today."):"Log your morning metrics to personalize today’s training.";$("todayHRV").textContent=d?.hrv??"—";$("todayRHR").textContent=d?.rhr??"—";$("todaySleep").textContent=d?.sleep??"—";const state={taskCheckin:!!d,taskWorkout:!!done,taskNutrition:taskDone("nutrition"),taskMobility:taskDone("mobility")};Object.entries(state).forEach(x=>{const el=$(x[0]);el.classList.toggle("done",x[1]);el.querySelector(".task-circle").textContent=x[1]?"✓":"○"});$("todayTaskCount").textContent=Object.values(state).filter(Boolean).length+"/4"}
function renderTrain(){const det=makeSession(sessionName()),c=todayCheckin(),label=!c?"CHECK IN":c.overall==="GREEN"?"PRIMARY":c.overall==="YELLOW"?"MODIFIED":"RECOVERY";$("workoutKicker").textContent="TODAY · WEEK "+currentWeek()+" · "+blockForWeek(currentWeek()).name.toUpperCase();$("workoutTitle").textContent=det.title;$("workoutWhy").textContent=det.why;$("workoutTags").innerHTML='<span>◷ '+det.duration+'</span><span>◈ '+det.effort+'</span><span>'+det.type+'</span>';$("sessionStatus").textContent=label;$("sessionStatus").className="session-status "+(!c?"yellow":c.overall==="YELLOW"?"yellow":c.overall==="RED"?"red":"");$("exerciseCount").textContent=det.steps.length+" movements";$("workoutPrescription").innerHTML=det.steps.map((e,i)=>'<button class="exercise-card" data-i="'+i+'"><div class="exercise-thumb">'+svg(e.name)+'</div><div class="exercise-copy"><strong>'+(i+1)+'. '+e.name+'</strong><span>'+e.dose+'</span><small>Rest: '+e.rest+'</small></div><b>›</b></button>').join("");$("workoutPrescription").querySelectorAll(".exercise-card").forEach(b=>b.onclick=()=>openExercise(det.steps[+b.dataset.i]));renderLibrary()}
function libraryExercises(){const map=new Map();[...A,...B,ex("RKC plank","3 × 20–40 sec","60 sec","Squeeze glutes, quads and abs hard.","Core"),ex("Push-ups","4–6 submaximal sets","2 min","Strict reps; stop before failure.","Bodyweight"),ex("Easy row","30–60 min","Continuous","Conversational effort.","Row")].forEach(e=>map.set(e.name,e));return[...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function renderLibrary(q=""){const all=libraryExercises(),query=q.trim().toLowerCase(),arr=query?all.filter(e=>(e.name+" "+e.type+" "+e.cue).toLowerCase().includes(query)):all;if($("libraryCount"))$("libraryCount").textContent=arr.length+" exercise"+(arr.length===1?"":"s");$("exerciseLibrary").innerHTML=arr.length?arr.map((e,i)=>'<button class="library-item" data-i="'+i+'"><div class="library-thumb">'+svg(e.name)+'</div><div><strong>'+e.name+'</strong><small>'+e.type+' · '+e.dose+'</small></div><b>›</b></button>').join(""):'<div class="empty-search">No matching exercises.</div>';$("exerciseLibrary").querySelectorAll(".library-item").forEach(b=>b.onclick=()=>openExercise(arr[+b.dataset.i]))}
function dateFor(w,i){const d=new Date(programStart());d.setHours(12,0,0,0);d.setDate(d.getDate()+(w-1)*7+i);return d}
function renderWeek(){const w=viewedWeek,bl=blockForWeek(w),days=daysFor(bl),hist=workouts(),st=dateFor(w,0),en=dateFor(w,6);$("weekTitle").textContent="Week "+w;$("weekRange").textContent=st.toLocaleDateString(undefined,{month:"short",day:"numeric"})+" – "+en.toLocaleDateString(undefined,{month:"short",day:"numeric"});$("weekSummary").innerHTML='<div class="week-card"><div class="week-overview"><small>'+bl.name.toUpperCase()+'</small><strong>'+bl.focus+'</strong><p>'+bl.run+' · '+bl.ruck+'</p></div>'+days.map((name,i)=>{const det=makeSession(name),date=dateFor(w,i),is=date.toDateString()===todayKey(),done=hist.some(x=>x.week===w&&new Date(x.date).toDateString()===date.toDateString()&&x.completed==="YES");return'<div class="day-row '+(done?"done ":"")+(is?"today-row":"")+'"><button class="day-button" data-i="'+i+'"><div class="day-date"><strong>'+DAY[i]+'</strong><small>'+date.getDate()+'</small></div><span class="day-state">'+(done?"✓":"○")+'</span><div class="day-desc"><strong>'+det.title+'</strong><small>'+det.type+' · '+det.effort+'</small></div><span class="day-chevron">⌄</span></button><div class="day-detail"></div></div>'}).join("")+'</div>';$("weekSummary").querySelectorAll(".day-button").forEach(btn=>btn.onclick=()=>{const row=btn.closest(".day-row"),was=row.classList.contains("open"),i=+btn.dataset.i;$("weekSummary").querySelectorAll(".day-row.open").forEach(x=>{x.classList.remove("open");x.querySelector(".day-detail").innerHTML=""});if(!was){const det=makeSession(days[i]);row.classList.add("open");row.querySelector(".day-detail").innerHTML='<div class="day-detail-inner"><p>'+det.why+'</p>'+det.steps.map((e,j)=>'<div class="mini-exercise"><b>'+(j+1)+'</b><div><strong>'+e.name+'</strong><small>'+e.dose+' · Rest '+e.rest+'</small></div></div>').join("")+'</div>'}})}
const milestones={default:["Log at least 7 morning check-ins","Complete at least 4 strength-oriented sessions","Complete at least 4 aerobic/run sessions","Complete at least 14 total phase days"]};
function phaseComplete(bl){const hs=workouts().filter(x=>x.week>=bl.start&&x.week<=bl.end&&x.completed==="YES"),total=(bl.end-bl.start+1)*7,done=new Set(hs.map(x=>new Date(x.date).toDateString())).size;return{done,total,pct:Math.min(100,Math.round(done/total*100))}}
const macroPhases=[["Rebuild",1,12,"Recondition, build aerobic base and restore tissue tolerance."],["Build",13,24,"Increase running, weighted-pack walking and controlled faster work."],["Specificity",25,40,"Shift toward running, loaded movement, bodyweight strength and consecutive-day durability."],["Work Capacity",41,52,"Build high accumulated workload and prolonged time on feet."],["Taper",53,56,"Dissipate fatigue while retaining selected intensity."]];
function macroForWeek(w){const x=macroPhases.find(p=>w>=p[1]&&w<=p[2])||macroPhases[0];return{name:x[0],start:x[1],end:x[2],focus:x[3]}}
function macroComplete(p){const hs=workouts().filter(x=>x.week>=p.start&&x.week<=p.end&&x.completed==="YES"),total=(p.end-p.start+1)*7,done=new Set(hs.map(x=>new Date(x.date).toDateString())).size;return{done,total,pct:Math.min(100,Math.round(done/total*100))}}
function renderProgram(){const current=macroForWeek(currentWeek()),pc=macroComplete(current),sub=blockForWeek(currentWeek()),m=milestones.default,phW=workouts().filter(x=>x.week>=current.start&&x.week<=current.end&&x.completed==="YES"),phL=logs().filter(x=>x.week>=current.start&&x.week<=current.end),strengthN=phW.filter(x=>/strength|carry/i.test(x.session||"")).length,aerobicN=phW.filter(x=>/run|row|aerobic|recovery/i.test(x.session||"")).length,ms=[phL.length>=7,strengthN>=4,aerobicN>=4,pc.done>=14],cm=ms.filter(Boolean).length;$("currentPhaseCard").innerHTML='<div class="phase-feature-top"><div><small>PHASE '+(macroPhases.findIndex(x=>x[0]===current.name)+1)+' OF '+macroPhases.length+'</small><h2>'+current.name+'</h2><p>Weeks '+current.start+'–'+current.end+'<br>'+current.focus+'<br><br><b>Current block:</b> '+sub.name+'</p></div></div><div class="phase-progress-box"><div class="phase-ring" style="--p:'+pc.pct+'"><span>'+pc.pct+'%</span></div><div class="phase-progress-copy"><strong>'+pc.done+' of '+pc.total+' days completed</strong><small>Daily completion across this phase</small><div class="progress-bar"><i style="width:'+pc.pct+'%"></i></div></div></div>';$("milestoneCount").textContent=cm+"/4";$("phaseMilestones").innerHTML=m.map((x,i)=>'<div class="milestone '+(ms[i]?"done":"")+'"><span class="milestone-state">'+(ms[i]?"✓":"○")+'</span><div><strong>'+x+'</strong><small>'+(ms[i]?"Completed":"In progress")+'</small></div></div>').join("");$("programBlocks").innerHTML=macroPhases.map((x,i)=>{const p={name:x[0],start:x[1],end:x[2],focus:x[3]},c=macroComplete(p),cur=current.name===p.name;return'<div class="phase-card '+(cur?"current":"")+'"><span class="phase-num">'+(i+1)+'</span><div><strong>'+p.name+'</strong><small>Weeks '+p.start+'–'+p.end+'</small></div><span class="phase-pct">'+c.pct+'%</span></div>'}).join("")}
function draw(id,a){const c=$(id),ctx=c.getContext("2d"),w=c.clientWidth||320,h=160,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;ctx.scale(d,d);ctx.clearRect(0,0,w,h);if(a.length<2){ctx.fillStyle="#8fa8bd";ctx.font="12px -apple-system, BlinkMacSystemFont, sans-serif";ctx.fillText("Save more check-ins to build this trend.",10,80);return}const mn=Math.min(...a),mx=Math.max(...a),sp=mx-mn||1,p=12;ctx.strokeStyle="#1794ff";ctx.lineWidth=2.5;ctx.beginPath();a.forEach((v,i)=>{const x=p+i*(w-2*p)/(a.length-1),y=h-p-(v-mn)*(h-2*p)/sp;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function renderTrends(){const l=logs().slice(0,28).reverse(),map={RED:30,YELLOW:65,GREEN:90},wt=l.filter(x=>Number.isFinite(x.weight)).map(x=>x.weight);$("trendRecovery").textContent=l.length?l.length+" check-ins":"No data";$("trendWeight").textContent=wt.length?wt.at(-1).toFixed(1)+" lb":"No data";requestAnimationFrame(()=>{draw("recoveryChart",l.map(x=>x.score||map[x.overall]||50));draw("weightChart",wt)});const a=[...logs().map(x=>({...x,k:"Check-in"})),...workouts().map(x=>({...x,k:"Session"}))].sort((x,y)=>new Date(y.date)-new Date(x.date)).slice(0,8);$("trendLogList").innerHTML=a.length?a.map(x=>'<div class="log-card"><div><strong>'+(x.k==="Session"?x.session:"Morning check-in")+'</strong><small>'+new Date(x.date).toLocaleDateString()+' · Week '+x.week+'</small></div><small>'+(x.k==="Session"?(x.completed||""):(x.overall||""))+'</small></div>').join(""):'<div class="log-card"><small>No activity saved yet.</small></div>';countRecords()}
function openCheckin(){$("checkinSheet").classList.remove("hidden");requiredFields();bindInfo($("checkinSheet"))}function closeCheckin(){$("checkinSheet").classList.add("hidden")}function closeModal(){$("infoModal").classList.add("hidden")}function bindInfo(root){(root||document).querySelectorAll(".info-dot[data-term]").forEach(b=>b.onclick=e=>{e.stopPropagation();openInfo(b.dataset.term)})}
function switchTab(t){$("headerAction").style.display=t==="today"?"grid":"none";document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(t).classList.add("active");document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.target===t));$("pageTitle").textContent=t==="workout"?"Train":t.charAt(0).toUpperCase()+t.slice(1);$("todayDate").textContent=t==="today"?new Date().toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"}):"";window.scrollTo({top:0,left:0,behavior:"instant"});if(t==="workout")renderTrain();if(t==="week")renderWeek();if(t==="trends")renderTrends();if(t==="program")renderProgram()}
function renderAll(){applyBaselines();renderMissedBanner();renderToday();renderTrain();renderWeek();renderTrends();renderProgram();requiredFields();bindInfo(document)}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>switchTab(b.dataset.target));$("headerAction").onclick=()=>switchTab("week");$("taskCheckin").onclick=openCheckin;$("todayWorkoutCard").onclick=()=>switchTab("workout");$("taskWorkout").onclick=()=>switchTab("workout");$("taskNutrition").onclick=()=>{setTask("nutrition",!taskDone("nutrition"));renderToday()};$("taskMobility").onclick=()=>{setTask("mobility",!taskDone("mobility"));renderToday()};$("closeCheckin").onclick=closeCheckin;$("checkinSheet").onclick=e=>{if(e.target===$("checkinSheet"))closeCheckin()};$("evaluateBtn").onclick=evaluate;$("saveBtn").onclick=saveCheckin;$("completeWorkoutQuick").onclick=()=>saveWorkout("YES");$("completeWorkout").onclick=()=>saveWorkout(val("completed")||"YES");$("modalClose").onclick=closeModal;$("modalDone").onclick=closeModal;$("infoModal").onclick=e=>{if(e.target===$("infoModal"))closeModal()};$("prevWeek").onclick=()=>{viewedWeek=Math.max(1,viewedWeek-1);renderWeek()};$("nextWeek").onclick=()=>{viewedWeek=Math.min(56,viewedWeek+1);renderWeek()};if($("librarySearch"))$("librarySearch").addEventListener("input",e=>renderLibrary(e.target.value));document.querySelectorAll(".segment").forEach(b=>b.onclick=()=>{document.querySelectorAll(".segment").forEach(x=>x.classList.toggle("active",x===b));$("trainSessionView").classList.toggle("hidden",b.dataset.trainview!=="session");$("trainLibraryView").classList.toggle("hidden",b.dataset.trainview!=="library")});
["hrv","hrvBase","rhr","rhrBase","sleep","sleepQ","fatigue","grip","gripBase","load","pain","performance","weight","weightAvg"].forEach(id=>{const v=localStorage.getItem("input_"+id);if(v!==null)$(id).value=v;$(id).addEventListener("input",requiredFields);$(id).addEventListener("change",requiredFields)});$("focal").checked=localStorage.input_focal==="1";$("gait").checked=localStorage.input_gait==="1";
const DB_NAME="AdaptiveLandPrepDB",STORE="kv";function openDB(){return new Promise((r,j)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}async function dbSet(k,v){try{const d=await openDB();d.transaction(STORE,"readwrite").objectStore(STORE).put(v,k)}catch(e){}}async function requestPersistence(){let p=false;try{p=await navigator.storage?.persisted?.()||await navigator.storage?.persist?.()}catch(e){}$("persistBadge").textContent=p?"Persistent":"On device";$("dbStatus").textContent=p?"Persistent storage granted":"Local database active; keep periodic backups"}function countRecords(){$("recordCount").textContent=(logs().length+workouts().length)+" records";$("lastBackup").textContent=localStorage.lastBackupAt?new Date(localStorage.lastBackupAt).toLocaleString():"Never"}function exportBackup(){const p={app:"Adaptive Land Prep",formatVersion:2,exportedAt:new Date().toISOString(),data:{trainingLogs:localStorage.trainingLogs||"[]",workoutHistory:localStorage.workoutHistory||"[]",programStart:localStorage.programStart}},b=new Blob([JSON.stringify(p,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="adaptive-land-prep-backup.json";a.click();localStorage.lastBackupAt=p.exportedAt;countRecords()}async function importBackup(f){const o=JSON.parse(await f.text());if(o.app!=="Adaptive Land Prep")throw Error();Object.entries(o.data).forEach(x=>localStorage.setItem(x[0],x[1]));location.reload()}$("exportBackup").onclick=exportBackup;$("importBackup").onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]).catch(()=>alert("That backup could not be restored."));
$("headerAction").innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="5.5" width="16" height="14" rx="2.5"/><path d="M8 3.5v4M16 3.5v4M4 9.5h16"/></svg>';$("headerAction").style.display="grid";renderAll();requestPersistence();if("serviceWorker"in navigator)addEventListener("load",async()=>{const r=await navigator.serviceWorker.register("./service-worker.js");r.update();navigator.serviceWorker.addEventListener("controllerchange",()=>{if(!sessionStorage.swReloaded){sessionStorage.swReloaded="1";location.reload()}})});
