
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:null};
const val=id=>$(id)?.value||"";
const DAY=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const blocks=[
 ["Re-entry",1,4,"Up to 2 short run/walk sessions each week","No weighted-pack walking yet","Rebuild routine, aerobic fitness and basic tissue tolerance."],
 ["Foundation I",5,8,"2 runs each week · about 3–6 miles","2–4 miles easy with a light pack","Build continuous running tolerance and introduce loaded walking."],
 ["Foundation II",9,12,"2–3 runs each week · about 6–10 miles","3–5 miles easy","Build the aerobic base, bodyweight strength and loaded-carry durability."],
 ["Build I",13,16,"3 runs each week · about 10–16 miles","4–6 miles","Introduce controlled faster running while increasing loaded walking."],
 ["Build II",17,20,"3 runs each week · about 14–20 miles","5–8 miles","Grow the long run and weighted-pack walking while maintaining strength."],
 ["Build III",21,24,"3 runs each week · about 16–22 miles","6–10 miles","Consolidate the build and test aerobic/bodyweight progress."],
 ["Specificity I",25,28,"3–4 runs each week · about 20–26 miles","8–10 miles","Improve running economy, weighted-pack walking technique and carries."],
 ["Specificity II",29,32,"3–4 runs each week · about 22–30 miles","8–12 miles","Combine faster running with long aerobic work and loaded movement."],
 ["Specificity III",33,36,"4 runs each week · about 26–34 miles","10–14 miles","Build consecutive-day durability while maintaining strength."],
 ["Specificity IV",37,40,"3–4 runs each week · about 24–32 miles","10–14 miles","Absorb accumulated work and test durability."],
 ["Work Capacity I",41,44,"4 runs each week · about 28–38 miles","12–16 miles","Build large accumulated workload and time on feet."],
 ["Work Capacity II",45,48,"4–5 runs each week · about 34–45 miles","14–20 miles","Peak specificity and consecutive-day work."],
 ["Peak / Consolidate",49,52,"About 38–50 miles only if earned","16–24 miles only if earned","Assess peak work capacity without forcing arbitrary mileage."],
 ["Taper",53,56,"Reduce volume progressively","Reduce, then eliminate","Dissipate fatigue while retaining selected intensity."]
];
const templates={
 "Re-entry":["Recovery & mobility","Full-body strength — Session A","Easy aerobic row","Full-body strength — Session B","Easy aerobic row","Introductory run/walk","Easy row + trunk work"],
 "Foundation I":["Recovery & mobility","Full-body strength + bodyweight training","Easy aerobic row","Easy run + lower-leg durability","Full-body strength — Session B","Long easy run or light weighted-pack walk","Easy recovery row"],
 "Foundation II":["Recovery & mobility","Full-body strength + bodyweight training","Easy aerobic row","Easy run + lower-leg durability","Full-body strength — Session B","Long easy run or light weighted-pack walk","Easy recovery row"],
 "Build I":["Recovery & mobility","Quality run + strength","Easy run","Rowing threshold work","Strength + bodyweight training","Long run or weighted-pack walk","Easy recovery row"],
 "Build II":["Recovery & mobility","Quality run + strength","Easy run","Easy aerobic row","Strength + bodyweight training","Long run or weighted-pack walk","Easy recovery row"],
 "Build III":["Recovery & mobility","Quality run","Easy run + strength","Easy aerobic row","Strength + bodyweight training","Long run or weighted-pack walk","Easy recovery row"],
 "Specificity I":["Recovery & mobility","Quality run + bodyweight training","Easy run","Strength + easy row","Easy run + loaded carries","Long weighted-pack walk or run","Recovery aerobic work"],
 "Specificity II":["Recovery & mobility","Quality run + bodyweight training","Easy run","Strength + easy row","Easy run + loaded carries","Long weighted-pack walk or run","Recovery aerobic work"],
 "Specificity III":["Recovery & mobility","Quality run","Easy run","Strength + loaded carries","Easy run","Long weighted-pack walk or run","Recovery aerobic work"],
 "Specificity IV":["Recovery & mobility","Quality run","Easy run","Strength + easy row","Easy run","Long weighted-pack walk or run","Recovery aerobic work"],
 "Work Capacity I":["Recovery & mobility","Quality run","Medium aerobic run","Strength + loaded carries","Easy run","Long weighted-pack walk or run","Easy aerobic work while fatigued"],
 "Work Capacity II":["Recovery & mobility","Quality run","Medium aerobic run","Strength + loaded carries","Easy run","Long weighted-pack walk or run","Easy aerobic work while fatigued"],
 "Peak / Consolidate":["Recovery & mobility","Specific hard session","Medium aerobic run","Carries + strength maintenance","Easy run","Peak specific session","Recovery aerobic work"],
 "Taper":["Recovery & mobility","Short quality session","Easy aerobic work","Light strength","Easy aerobic work","Short specific session","Recovery"]
};
const ex=(name,dose,rest,cue,type)=>({name,dose,rest,cue,type:type||"Strength"});
const A=[ex("Back squat","3 × 5","2–3 min","Keep the whole foot planted and finish each rep tall."),ex("Romanian deadlift","3 × 6–8","2–3 min","Push the hips back while keeping the spine neutral."),ex("Overhead press","3 × 5","2 min","Brace the trunk and press without leaning backward."),ex("Pull-ups","3–5 submaximal sets","2 min","Stop before form breaks. Use a resistance band if needed.","Bodyweight"),ex("Tibialis raises","3 × 15–25","60–90 sec","Lift the forefoot toward the shin through a controlled range.","Durability"),ex("Calf / soleus raises","3 × 12–20","60–90 sec","Use straight-knee and bent-knee variations across the week.","Durability"),ex("Neck harness","2–3 sets each direction","60 sec","Use light load and smooth motion. Never jerk the neck.","Durability"),ex("Grip work","2–3 sets","60–90 sec","Use hangs, carries or grip tools without max testing.","Durability")];
const B=[ex("Split squat or reverse lunge","3 × 6–8 each leg","2 min","Stay balanced and keep the front foot planted."),ex("Hip hinge","3 × 6–8","2–3 min","Use a deadlift or dumbbell hinge with a neutral spine."),ex("Press + row","3 × 6–10 each","90–120 sec","Pair a horizontal press with a controlled row."),ex("Suitcase carry","3 × 40–100 m each side","As needed","Walk tall without leaning toward the weight.","Carry"),ex("Tibialis + soleus","3 sets each","60–90 sec","Control the full range rather than bouncing.","Durability"),ex("Neck harness","2–3 controlled sets","60 sec","Keep the load modest.","Durability"),ex("Forearm roller","2–3 climbs","60–90 sec","Use smooth wrist flexion and extension.","Durability")];
const definitions={readiness:"A daily signal built from recovery, pain/movement and fueling information. It changes training stress; it is not a medical diagnosis.",HRV:"Heart-rate variability is the beat-to-beat variation in time between heartbeats. The app compares your value with your own history.","resting heart rate":"Your heart rate when rested, ideally measured under similar morning conditions.","grip strength":"A standardized grip measurement used as one small neuromuscular readiness signal.","session effort":"Your overall rating of how hard the session felt: 1 is extremely easy and 10 is maximal.",threshold:"A hard but controlled intensity that can be sustained for meaningful work.","RKC plank":"A high-tension forearm plank: squeeze glutes, quads and abs hard while holding a straight body line."};
function mondayDate(src){const d=new Date(src||Date.now()),i=(d.getDay()+6)%7;d.setHours(12,0,0,0);d.setDate(d.getDate()-i);return d}
function programStart(){return localStorage.programStart?new Date(localStorage.programStart):new Date()}
function currentWeek(){if(!localStorage.programStart)return 1;const start=new Date(localStorage.programStart),now=new Date();start.setHours(12,0,0,0);now.setHours(12,0,0,0);return Math.max(1,Math.min(56,Math.floor((now-start)/604800000)+1))}
let viewedWeek=currentWeek();
function blockForWeek(w){const b=blocks.find(x=>w>=x[1]&&w<=x[2])||blocks[0];return{name:b[0],start:b[1],end:b[2],run:b[3],ruck:b[4],focus:b[5]}}
function daysFor(b){return templates[b.name]||templates["Re-entry"]}
function dayIndex(){if(!localStorage.programStart)return 0;const a=new Date(programStart()),b=new Date();a.setHours(12,0,0,0);b.setHours(12,0,0,0);const days=Math.floor((b-a)/86400000);return((days%7)+7)%7}
function sessionName(){const b=blockForWeek(currentWeek());return daysFor(b)[dayIndex()]}
function makeSession(name){
 const row=mins=>[ex("Warm-up",mins,"—","Start easy and build gradually.","Warm-up")];
 if(name==="Full-body strength — Session A")return{title:name,type:"Full Body",duration:"55–75 min",effort:"Moderate",why:"Build fundamental strength for running, loaded walking, posture and injury resistance.",steps:A};
 if(name==="Full-body strength — Session B")return{title:name,type:"Full Body",duration:"55–75 min",effort:"Moderate",why:"Build unilateral leg strength, trunk stability and loaded-carry durability.",steps:B};
 if(name.includes("Quality run + bodyweight"))return{title:name,type:"Run + Bodyweight",duration:"60–85 min",effort:"Hard / controlled",why:"Develop faster running while maintaining strict push-up and pull-up capacity.",steps:[ex("Quality run","Use quality-run structure","—","Complete the faster running first.","Run"),ex("Push-ups","4–6 submaximal sets","2 min","Strict reps; stop before failure.","Bodyweight"),ex("Pull-ups","4–6 submaximal sets","2 min","Strict or assisted.","Bodyweight"),ex("RKC plank","3 × 20–40 sec","60 sec","Squeeze glutes, quads and abs hard.","Core")]}; if(name.includes("Easy run + loaded carries"))return{title:name,type:"Run + Carry",duration:"60–90 min",effort:"Moderate",why:"Combine running durability with posture and awkward-load capacity.",steps:[ex("Easy run","Use current phase target","Continuous","Conversational pace.","Run"),ex("Bear-hug sandbag carry","3–5 rounds","As needed","Use a manageable load.","Carry"),ex("Suitcase carry","3 rounds each side","As needed","Stay tall without leaning.","Carry")]}; if(name.includes("bodyweight training"))return{title:name,type:"Full Body",duration:"60–80 min",effort:"Moderate",why:"Maintain strength while improving strict push-up and pull-up capacity.",steps:[...A.slice(0,4),ex("Push-ups","4–6 submaximal sets","2 min","Leave 2–4 clean reps in reserve.","Bodyweight"),ex("RKC plank","3 × 20–40 sec","60 sec","Squeeze glutes, quads and abs hard; keep a straight line.","Core")]};
 if(name.includes("Strength + loaded carries")||name.includes("Carries + strength"))return{title:name,type:"Strength + Carry",duration:"60–85 min",effort:"Moderate",why:"Maintain force production and train posture under external load.",steps:[...B.slice(0,3),ex("Sandbag bear-hug carry","3–5 rounds","As needed","Walk under control.","Carry"),ex("Suitcase carry","3 rounds each side","As needed","Stay tall without leaning.","Carry")]};
 if(name.includes("Strength + easy row"))return{title:name,type:"Strength + Aerobic",duration:"70–100 min",effort:"Moderate",why:"Maintain strength and add low-impact aerobic volume.",steps:[...B.slice(0,4),ex("Easy row","30–45 min","Continuous","Keep a conversational effort.","Row")]};
 if(name.includes("strength")&&name.includes("run"))return{title:name,type:"Run + Strength",duration:"70–100 min",effort:"Moderate / hard",why:"Develop running while preserving strength.",steps:[...row("15 min"),ex("Controlled quality run","20–30 min total","Variable","Hard but controlled; never all-out.","Run"),...A.slice(0,3)]};
 if(name.includes("Easy aerobic row"))return{title:name,type:"Aerobic",duration:"50–90 min",effort:"Easy",why:"Build the aerobic engine with minimal impact.",steps:[ex("Warm-up row","5–10 min","—","Very easy rowing.","Row"),ex("Main aerobic row","40–75 min","Continuous","Conversational effort.","Row"),ex("Cool-down row","5 min","—","Very easy.","Row")]};
 if(name.includes("recovery row")||name.includes("Recovery aerobic"))return{title:name,type:"Recovery",duration:"25–60 min",effort:"Very easy",why:"Support recovery while preserving aerobic rhythm.",steps:[ex("Easy row or walk","25–60 min","Continuous","Finish feeling better than you started.","Aerobic")]};
 if(name.includes("row")&&name.includes("trunk"))return{title:name,type:"Aerobic + Core",duration:"45–70 min",effort:"Easy",why:"Build aerobic capacity and trunk stiffness.",steps:[ex("Easy row","30–60 min","Continuous","Conversational effort.","Row"),ex("RKC plank","3 × 20–40 sec","60 sec","Squeeze glutes, quads and abs hard.","Core"),ex("Suitcase carry","3 rounds each side","As needed","Stay tall and breathe under control.","Carry")]};
 if(name.includes("Rowing threshold"))return{title:name,type:"Aerobic",duration:"35–60 min",effort:"Moderate / hard",why:"Develop higher aerobic power with low mechanical cost.",steps:[ex("Warm-up row","10 min","—","Easy.","Row"),ex("Controlled threshold work","20–40 min total","Variable","Hard but controlled; do not force a universal number.","Row"),ex("Cool-down row","5–10 min","—","Easy.","Row")]};
 if(name.includes("Recovery & mobility"))return{title:name,type:"Recovery",duration:"25–45 min",effort:"Very easy",why:"Reduce fatigue while keeping the body moving and joints comfortable.",steps:[ex("Easy walk or row","20–30 min","Continuous","Very easy.","Aerobic"),ex("Ankle mobility","2 × 8–10 each side","—","Move through pain-free range.","Mobility"),ex("Hip mobility","5–10 min","—","Gentle controlled movement.","Mobility"),ex("Light trunk work","2–3 easy sets","60 sec","Plank, side plank or dead bug.","Core")]};
 if(name.includes("Introductory run/walk"))return{title:name,type:"Run",duration:"20–40 min",effort:"Easy",why:"Reintroduce running-specific bone, tendon and foot stress without unnecessary overload.",steps:[ex("Warm-up walk","5–10 min","—","Brisk but comfortable.","Run"),ex("Run / walk","10–25 min total","Alternate as needed","Keep it easy. Stop for focal pain or altered gait.","Run"),ex("Cool-down walk","5 min","—","Easy.","Run")]};
 if(name.includes("lower-leg durability"))return{title:name,type:"Run + Durability",duration:"45–70 min",effort:"Easy",why:"Pair controlled running with targeted shin, calf and ankle strengthening.",steps:[ex("Easy run","Use current phase target","Continuous","Conversational pace.","Run"),ex("Tibialis raises","3 × 20","60 sec","Control the movement.","Durability"),ex("Seated soleus raises","3 × 15–20","60–90 sec","Use moderate load.","Durability"),ex("Eccentric calf raises","3 × 12–15","60–90 sec","Lower slowly.","Durability")]};
 if(name.includes("Quality run"))return{title:name,type:"Run",duration:"45–75 min",effort:"Hard / controlled",why:"Improve sustainable speed after aerobic and tissue tolerance are established.",steps:[ex("Warm-up","15–20 min","—","Easy jog plus relaxed strides.","Run"),ex("Main quality work","Phase-specific intervals or tempo","Variable","Use individual pace, heart-rate and lactate data.","Run"),ex("Cool-down","10–15 min","—","Easy jog.","Run")]};
 if(name.includes("Medium aerobic run"))return{title:name,type:"Run",duration:"45–75 min",effort:"Easy / moderate",why:"Accumulate meaningful running volume between easy and long sessions.",steps:[ex("Medium run","Use weekly allocation","Continuous","Stay below threshold and finish controlled.","Run")]};
 if(name.includes("Easy run"))return{title:name,type:"Run",duration:"Varies",effort:"Easy",why:"Build running-specific aerobic fitness and tissue tolerance.",steps:[ex("Warm-up","5–10 min","—","Walk or jog easily.","Run"),ex("Main run","Use this week’s mileage allocation","Continuous","Conversational pace; do not chase speed.","Run"),ex("Cool-down","5–10 min","—","Easy jog or walk.","Run")]};
 if(name.includes("Long"))return{title:name,type:"Endurance",duration:"Long",effort:"Easy / moderate",why:"Build time-on-feet and loaded-movement durability.",steps:[ex("Long session","Use current weekly target","Continuous","Increase distance before pack load; keep gait normal.","Endurance")]};
 if(name.includes("Light strength"))return{title:name,type:"Strength",duration:"35–50 min",effort:"Easy",why:"Retain movement quality during taper without creating soreness.",steps:[ex("Squat","2 × 5","2 min","Use about 60–70% of normal training load."),ex("Hinge","2 × 6","2 min","Easy to moderate."),ex("Press","2 × 5","90 sec","Easy."),ex("Pull-ups","2–3 easy sets","90 sec","No failure.","Bodyweight")]};
 return{title:name,type:"Specific",duration:"30–60 min",effort:"Controlled",why:"Complete the current phase-specific session with clean technique and adaptive restraint.",steps:[ex("Main session","Follow current block target","—","Stop for focal pain, altered gait or red recovery flags.","Specific")]};
}
function logs(){return JSON.parse(localStorage.trainingLogs||"[]")}function workouts(){return JSON.parse(localStorage.workoutHistory||"[]")}
function todayKey(){return new Date().toDateString()}function todayCheckin(){return logs().find(x=>new Date(x.date).toDateString()===todayKey())}function todayWorkout(){return workouts().find(x=>new Date(x.date).toDateString()===todayKey()&&x.completed==="YES")}
function taskDone(k){return localStorage.getItem("task_"+k+"_"+todayKey())==="1"}function setTask(k,v){localStorage.setItem("task_"+k+"_"+todayKey(),v?"1":"0")}
function systemic(){const sl=num("sleep"),q=num("sleepQ"),f=num("fatigue"),h=num("hrv"),hb=num("hrvBase"),r=num("rhr"),rb=num("rhrBase"),g=num("grip"),gb=num("gripBase"),p=val("performance");if([sl,q,f,h,r].every(x=>x===null)&&!p)return"";if((sl!==null&&sl<6)||(q!==null&&q<=2)||(f!==null&&f>=4)||(hb&&h!==null&&h<.85*hb)||(rb&&r!==null&&r>rb+8)||p==="NO")return"RED";if((sl!==null&&sl<7)||q===3||f===3||(hb&&h!==null&&h<.92*hb)||(rb&&r!==null&&r>rb+5)||(gb&&g!==null&&g<.9*gb))return"YELLOW";return"GREEN"}
function mechanical(){const p=num("pain");if(p===null&&!$("focal").checked&&!$("gait").checked)return"";if($("focal").checked||$("gait").checked||(p!==null&&p>=5))return"RED";if(p!==null&&p>=3)return"YELLOW";return"GREEN"}
function fueling(){const w=num("weight"),a=num("weightAvg"),l=num("load");if(w===null||a===null||l===null)return"";if(w<a*.985&&l>=7)return"RED";if(w<a*.99&&l>=5)return"YELLOW";return"GREEN"}
function decision(){const a=systemic(),b=mechanical(),c=fueling(),o=!a&&!b&&!c?"":(a==="RED"||b==="RED"?"RED":(a==="YELLOW"||b==="YELLOW"||c==="RED"?"YELLOW":"GREEN"));let score=92;if(a==="YELLOW")score-=18;if(a==="RED")score-=42;if(b==="YELLOW")score-=18;if(b==="RED")score-=55;if(c==="YELLOW")score-=8;if(c==="RED")score-=16;score=Math.max(15,Math.min(98,score));let run="Full phase plan",ruck="Full phase plan",row="Phase plan",strength="Full plan",intensity="Planned",nutrition="Follow phase target",warning="";if(!o)return{a,b,c,o,score:0,run:"Complete check-in",ruck:"Complete check-in",row:"Complete check-in",strength:"Complete check-in",intensity:"Complete check-in",nutrition:"Complete check-in",warning:""};if(b==="RED"){run="No running";ruck="No weighted-pack walking";row="Easy row if pain-free";strength="Non-aggravating only";intensity="No hard training";warning="Mechanical override: favorable recovery metrics do not justify impact or loaded walking."}else if(o==="RED"){run="Row or walk only";ruck="No loaded walking";row="Recovery row";strength="Reduce about 50%";intensity="No hard training"}else if(o==="YELLOW"){run="Reduce about 25–40%; keep easy";ruck="Reduce distance/load";row="Prefer easy rowing";strength="Reduce about 30%";intensity="No hard intervals"}if(c==="RED")nutrition="Add energy/carbohydrate; review deficit";else if(c==="YELLOW")nutrition="Hold intake; add carbohydrate around training";return{a,b,c,o,score,run,ruck,row,strength,intensity,nutrition,warning}}
function dayKey(d){return new Date(d).toDateString()}
function missedDays(){if(!localStorage.programStart)return[];const start=new Date(localStorage.programStart),end=new Date();start.setHours(12,0,0,0);end.setHours(12,0,0,0);end.setDate(end.getDate()-1);const resolved=new Set(logs().map(x=>dayKey(x.date))),failed=new Set(JSON.parse(localStorage.failedDays||"[]")),out=[];for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const k=d.toDateString();if(!resolved.has(k)&&!failed.has(k))out.push(new Date(d))}return out}
function markMissedDay(d){const arr=JSON.parse(localStorage.failedDays||"[]"),k=dayKey(d);if(!arr.includes(k))arr.push(k);localStorage.failedDays=JSON.stringify(arr);renderAll()}
function renderMissedBanner(){const m=missedDays(),b=$("missedDayBanner");if(!b)return;if(!m.length){b.classList.add("hidden");b.innerHTML="";return}const d=m[0];b.classList.remove("hidden");b.innerHTML='<div class="missed-icon">!</div><div><small>CURRICULUM DEBT</small><strong>Missed check-in · '+d.toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"})+'</strong><p>Resolve this day before it can count toward phase mastery.</p><div class="missed-actions"><button id="failMissed">Mark missed</button></div></div>';$("failMissed").onclick=()=>markMissedDay(d)}
function requiredFields(){const ids=["hrv","rhr","sleep","sleepQ","fatigue","load","pain","performance","weight"];let done=0;ids.forEach(id=>{const el=$(id),ok=String(el.value).trim()!=="";done+=ok?1:0;el.closest(".field").classList.toggle("field-done",ok);el.closest(".field").classList.toggle("field-needed",!ok)});const left=ids.length-done,b=$("checkinProgress");if(left===0){b.classList.add("complete");b.querySelector(".attention-icon").textContent="✓";b.querySelector("strong").textContent="Ready to evaluate";$("checkinProgressText").textContent="Required fields complete."}else{b.classList.remove("complete");b.querySelector(".attention-icon").textContent="!";b.querySelector("strong").textContent="Needs attention";$("checkinProgressText").textContent=left+" required field"+(left===1?"":"s")+" remaining."}}
function avg(a){const x=a.filter(Number.isFinite);return x.length?x.reduce((p,c)=>p+c,0)/x.length:null}
function applyBaselines(){const l=logs(),hb=avg(l.slice(0,28).map(x=>x.hrv)),rb=avg(l.slice(0,28).map(x=>x.rhr)),gb=avg(l.slice(0,28).map(x=>x.grip)),wa=avg(l.slice(0,7).map(x=>x.weight));if(hb!==null)$("hrvBase").value=hb.toFixed(0);if(rb!==null)$("rhrBase").value=rb.toFixed(0);if(gb!==null)$("gripBase").value=gb.toFixed(1);if(wa!==null)$("weightAvg").value=wa.toFixed(1)}
function persistInputs(){["hrv","hrvBase","rhr","rhrBase","sleep","sleepQ","fatigue","grip","gripBase","load","pain","performance","weight","weightAvg"].forEach(id=>localStorage.setItem("input_"+id,$(id).value));localStorage.input_focal=$("focal").checked?"1":"0";localStorage.input_gait=$("gait").checked?"1":"0"}
function evaluate(){const d=decision();[["sysStatus",d.a],["mechStatus",d.b],["fuelStatus",d.c]].forEach(x=>{$(x[0]).textContent=x[1]||"—";$(x[0]).style.color=x[1]==="GREEN"?"var(--green)":x[1]==="YELLOW"?"var(--yellow)":x[1]==="RED"?"var(--red)":""});[["runDecision",d.run],["ruckDecision",d.ruck],["c2Decision",d.row],["strengthDecision",d.strength],["intensityDecision",d.intensity],["nutritionDecision",d.nutrition]].forEach(x=>$(x[0]).textContent=x[1]);$("warningBox").textContent=d.warning;$("warningBox").classList.toggle("hidden",!d.warning);$("results").classList.remove("hidden");persistInputs()}
function saveCheckin(){evaluate();const d=decision();if(!d.o)return;if(!localStorage.programStart)localStorage.programStart=new Date().toISOString();const l=logs();l.unshift({date:new Date().toISOString(),week:currentWeek(),weight:num("weight"),hrv:num("hrv"),rhr:num("rhr"),grip:num("grip"),sleep:num("sleep"),overall:d.o,score:d.score});localStorage.trainingLogs=JSON.stringify(l.slice(0,365));dbSet("trainingLogs",localStorage.trainingLogs);setTask("checkin",true);closeCheckin();renderAll()}
function saveWorkout(c){const arr=workouts(),name=sessionName();arr.unshift({date:new Date().toISOString(),week:currentWeek(),session:name,rpe:num("sessionRPE"),duration:num("sessionDuration"),postPain:num("postPain"),completed:c||"YES",note:val("sessionNote")});localStorage.workoutHistory=JSON.stringify(arr.slice(0,500));dbSet("workoutHistory",localStorage.workoutHistory);setTask("workout",true);$("completionBanner").classList.remove("hidden");setTimeout(()=>$("completionBanner").classList.add("hidden"),1600);renderAll()}
function svg(name){
 const low=name.toLowerCase();
 const pose=low.includes("plank")?"plank":low.includes("squat")||low.includes("lunge")?"squat":low.includes("deadlift")||low.includes("hinge")||low.includes("romanian")?"hinge":low.includes("pull-up")||low.includes("pull up")||low.includes("hang")?"pull":low.includes("press")?"press":low.includes("carry")||low.includes("walk")?"carry":low.includes("row")?"row":low.includes("run")?"run":low.includes("calf")||low.includes("soleus")||low.includes("tibialis")?"calf":"stand";
 const skin="#e7b18a",shirt="#dbeefe",shorts="#2b5877",limb="#d0e6f5",metal="#edf5fb",shadow="#31536b";
 const head=(x,y,r=15)=>'<circle cx="'+x+'" cy="'+y+'" r="'+r+'" fill="'+skin+'"/><path d="M'+(x-r*.75)+' '+(y-r*.45)+' Q'+x+' '+(y-r*1.15)+' '+(x+r*.75)+' '+(y-r*.45)+'" stroke="#473427" stroke-width="5" stroke-linecap="round"/>';
 const torso=(x,y,w,h,rot=0)=>'<g transform="rotate('+rot+' '+x+' '+y+')"><rect x="'+(x-w/2)+'" y="'+(y-h/2)+'" width="'+w+'" height="'+h+'" rx="'+(w*.24)+'" fill="'+shirt+'"/><path d="M'+(x-w*.34)+' '+(y-h*.08)+' Q'+x+' '+(y+h*.2)+' '+(x+w*.34)+' '+(y-h*.08)+'" stroke="#b6d5eb" stroke-width="3" fill="none"/></g>';
 const limbLine=(x1,y1,x2,y2,w=10,color=limb)=>'<line x1="'+x1+'" y1="'+y1+'" x2="'+x2+'" y2="'+y2+'" stroke="'+color+'" stroke-width="'+w+'" stroke-linecap="round"/>';
 const joint=(x,y,r=5)=>'<circle cx="'+x+'" cy="'+y+'" r="'+r+'" fill="'+limb+'"/>';
 let b='';
 if(pose==="plank"){b=head(72,103)+torso(142,118,82,32,8)+limbLine(105,118,92,164,9)+limbLine(129,121,122,165,9)+limbLine(178,125,232,140,12)+limbLine(232,140,270,150,10)+joint(232,140)+limbLine(176,128,228,151,9)+limbLine(228,151,264,157,8)+'<rect x="95" y="158" width="65" height="8" rx="4" fill="'+shadow+'"/>'}
 else if(pose==="squat"){b=head(160,48)+torso(160,91,54,68,0)+limbLine(137,79,108,96,10)+limbLine(183,79,212,96,10)+limbLine(146,123,116,158,13)+limbLine(116,158,94,201,12)+limbLine(174,123,204,158,13)+limbLine(204,158,226,201,12)+joint(116,158,6)+joint(204,158,6)+'<rect x="103" y="74" width="114" height="6" rx="3" fill="'+metal+'"/><rect x="92" y="68" width="12" height="18" rx="3" fill="'+metal+'"/><rect x="216" y="68" width="12" height="18" rx="3" fill="'+metal+'"/><path d="M142 114h36l-6 25h-24z" fill="'+shorts+'"/>'}
 else if(pose==="hinge"){b=head(119,62)+torso(158,91,60,70,31)+limbLine(146,104,139,163,9)+limbLine(167,113,169,164,9)+limbLine(190,117,199,187,12)+limbLine(199,187,225,205,10)+limbLine(184,121,182,190,11)+limbLine(182,190,158,207,9)+'<rect x="117" y="163" width="92" height="6" rx="3" fill="'+metal+'"/><rect x="109" y="155" width="10" height="22" rx="3" fill="'+metal+'"/><rect x="208" y="155" width="10" height="22" rx="3" fill="'+metal+'"/><path d="M180 113l30 18-12 21-31-17z" fill="'+shorts+'"/>'}
 else if(pose==="pull"){b='<rect x="74" y="28" width="172" height="7" rx="3.5" fill="'+metal+'"/>'+head(160,84)+torso(160,127,54,72)+limbLine(145,107,112,35,10)+limbLine(175,107,208,35,10)+limbLine(148,160,136,212,11)+limbLine(172,160,184,212,11)+'<path d="M140 151h40l-5 24h-30z" fill="'+shorts+'"/>'}
 else if(pose==="press"){b=head(160,65)+torso(160,114,56,78)+limbLine(142,95,117,50,10)+limbLine(178,95,203,50,10)+limbLine(117,50,117,26,9)+limbLine(203,50,203,26,9)+limbLine(148,151,137,211,12)+limbLine(172,151,183,211,12)+'<rect x="93" y="21" width="134" height="6" rx="3" fill="'+metal+'"/><rect x="83" y="14" width="12" height="20" rx="3" fill="'+metal+'"/><rect x="226" y="14" width="12" height="20" rx="3" fill="'+metal+'"/><path d="M141 145h38l-5 25h-28z" fill="'+shorts+'"/>'}
 else if(pose==="carry"){b=head(160,53)+torso(160,100,56,74)+limbLine(143,88,121,137,10)+limbLine(177,88,199,137,10)+limbLine(148,137,136,203,12)+limbLine(172,137,189,199,12)+'<rect x="103" y="133" width="30" height="46" rx="7" fill="'+metal+'"/><path d="M140 130h40l-6 27h-28z" fill="'+shorts+'"/>'}
 else if(pose==="row"){b=head(123,66)+torso(160,101,58,72,22)+limbLine(148,106,190,143,9)+limbLine(162,114,198,151,9)+limbLine(184,125,203,194,12)+limbLine(183,126,163,194,11)+'<rect x="195" y="140" width="48" height="7" rx="3" fill="'+metal+'"/><path d="M180 121l34 14-9 24-34-15z" fill="'+shorts+'"/>'}
 else if(pose==="run"){b=head(164,58)+torso(160,104,52,70,-8)+limbLine(140,89,112,127,9)+limbLine(180,91,205,66,9)+limbLine(147,137,113,177,12)+limbLine(113,177,79,192,10)+limbLine(172,136,205,168,12)+limbLine(205,168,227,211,10)+'<path d="M141 131h39l-4 24h-31z" fill="'+shorts+'"/>'}
 else if(pose==="calf"){b=head(160,54)+torso(160,102,54,72)+limbLine(145,91,122,137,9)+limbLine(175,91,198,137,9)+limbLine(149,137,143,201,12)+limbLine(171,137,177,201,12)+'<rect x="112" y="204" width="96" height="8" rx="4" fill="'+shadow+'"/><path d="M141 130h38l-5 25h-28z" fill="'+shorts+'"/>'}
 else{b=head(160,53)+torso(160,101,56,74)+limbLine(142,88,116,137,10)+limbLine(178,88,204,137,10)+limbLine(148,137,137,205,12)+limbLine(172,137,183,205,12)+'<path d="M140 130h40l-6 27h-28z" fill="'+shorts+'"/>'}
 return '<svg viewBox="0 0 320 240" role="img" aria-label="'+name+' illustration"><rect x="0" y="0" width="320" height="240" rx="20" fill="#10283d"/><ellipse cx="160" cy="216" rx="116" ry="8" fill="rgba(0,0,0,.18)"/>'+b+'</svg>'
}
function openInfo(t){$("modalTitle").textContent=t.charAt(0).toUpperCase()+t.slice(1);$("modalContent").innerHTML='<div class="modal-copy"><p>'+(definitions[t]||"Defined by the current session context.")+'</p></div>';$("infoModal").classList.remove("hidden")}
function openExercise(e){$("modalTitle").textContent=e.name;$("modalContent").innerHTML='<div class="exercise-visual">'+svg(e.name)+'</div><div class="modal-stats"><div><span>WORK</span><strong>'+e.dose+'</strong></div><div><span>REST</span><strong>'+e.rest+'</strong></div><div><span>TYPE</span><strong>'+e.type+'</strong></div></div><div class="modal-copy"><h3>How to perform it</h3><p>'+e.cue+'</p><h3>Key rule</h3><p>Use controlled technique and stop if pain changes your movement pattern.</p></div>';$("infoModal").classList.remove("hidden")}
function closeModal(){$("infoModal").classList.add("hidden")}function bindInfo(root){(root||document).querySelectorAll(".info-dot[data-term]").forEach(b=>b.onclick=e=>{e.stopPropagation();openInfo(b.dataset.term)})}
function renderToday(){const d=todayCheckin(),det=makeSession(sessionName()),done=todayWorkout();$("todayDate").textContent=new Date().toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"});$("todayWorkoutName").textContent=det.title;$("todayWorkoutType").textContent=det.type.toUpperCase();$("todayWorkoutMeta").textContent=det.duration+" · "+det.effort;$("taskWorkoutSub").textContent=done?"Completed today":"Follow the adaptive prescription";const score=d?.score||0;$("readinessScore").textContent=d?score:"—";$("scoreRing").style.setProperty("--score",score);$("scoreRing").style.setProperty("--ring",d?(d.overall==="GREEN"?"var(--green)":d.overall==="YELLOW"?"var(--yellow)":"var(--red)"):"var(--green)");$("readinessLabel").textContent=d?(d.overall==="GREEN"?"Good":d.overall==="YELLOW"?"Caution":"Recover"):"Check in";$("readinessLabel").style.color=d?(d.overall==="GREEN"?"var(--green)":d.overall==="YELLOW"?"var(--yellow)":"var(--red)"):"";$("readinessMessage").textContent=d?(d.overall==="GREEN"?"You’re ready for the planned session.":d.overall==="YELLOW"?"Train, but reduce today’s stress.":"Recovery takes priority today."):"Log your morning metrics to personalize today’s training.";$("todayHRV").textContent=d?.hrv??"—";$("todayRHR").textContent=d?.rhr??"—";$("todaySleep").textContent=d?.sleep??"—";const state={taskCheckin:!!d,taskWorkout:!!done,taskNutrition:taskDone("nutrition"),taskMobility:taskDone("mobility")};Object.entries(state).forEach(x=>{const el=$(x[0]);el.classList.toggle("done",x[1]);el.querySelector(".task-circle").textContent=x[1]?"✓":"○"});$("todayTaskCount").textContent=Object.values(state).filter(Boolean).length+"/4"}
function renderTrain(){const det=makeSession(sessionName()),c=todayCheckin(),label=!c?"CHECK IN":c.overall==="GREEN"?"PRIMARY":c.overall==="YELLOW"?"MODIFIED":"RECOVERY";$("workoutKicker").textContent="TODAY · WEEK "+currentWeek()+" · "+blockForWeek(currentWeek()).name.toUpperCase();$("workoutTitle").textContent=det.title;$("workoutWhy").textContent=det.why;$("workoutTags").innerHTML='<span>◷ '+det.duration+'</span><span>◈ '+det.effort+'</span><span>'+det.type+'</span>';$("sessionStatus").textContent=label;$("sessionStatus").className="session-status "+(!c?"yellow":c.overall==="YELLOW"?"yellow":c.overall==="RED"?"red":"");$("exerciseCount").textContent=det.steps.length+" movements";$("workoutPrescription").innerHTML=det.steps.map((e,i)=>'<button class="exercise-card" data-i="'+i+'"><div class="exercise-thumb">'+svg(e.name)+'</div><div class="exercise-copy"><strong>'+(i+1)+'. '+e.name+'</strong><span>'+e.dose+'</span><small>Rest: '+e.rest+'</small></div><b>›</b></button>').join("");$("workoutPrescription").querySelectorAll(".exercise-card").forEach(b=>b.onclick=()=>openExercise(det.steps[+b.dataset.i]));renderLibrary()}
function libraryExercises(){const map=new Map();[...A,...B,ex("RKC plank","3 × 20–40 sec","60 sec","Squeeze glutes, quads and abs hard.","Core"),ex("Push-ups","4–6 submaximal sets","2 min","Strict reps; stop before failure.","Bodyweight"),ex("Easy row","30–60 min","Continuous","Conversational effort.","Row")].forEach(e=>map.set(e.name,e));return[...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function renderLibrary(q=""){const all=libraryExercises(),query=q.trim().toLowerCase(),arr=query?all.filter(e=>(e.name+" "+e.type+" "+e.cue).toLowerCase().includes(query)):all;if($("libraryCount"))$("libraryCount").textContent=arr.length+" exercise"+(arr.length===1?"":"s");$("exerciseLibrary").innerHTML=arr.length?arr.map((e,i)=>'<button class="library-item" data-i="'+i+'"><div class="library-thumb">'+svg(e.name)+'</div><div><strong>'+e.name+'</strong><small>'+e.type+' · '+e.dose+'</small></div><b>›</b></button>').join(""):'<div class="empty-search">No matching exercises.</div>';$("exerciseLibrary").querySelectorAll(".library-item").forEach(b=>b.onclick=()=>openExercise(arr[+b.dataset.i]))}
function dateFor(w,i){const d=new Date(programStart());d.setHours(12,0,0,0);d.setDate(d.getDate()+(w-1)*7+i);return d}
let viewedMonth=new Date();
const phasePalette={"Rebuild":"#48a7ff","Build":"#7d8cff","Specificity":"#ad73e6","Work Capacity":"#ef9a57","Taper":"#55cfa0"};
function isHighVolumeSession(name){return /long|quality|threshold|specific|medium aerobic/i.test(name)}
function nutritionForWeek(w,name){const high=isHighVolumeSession(name);if(w<=20)return{phase:"Aggressive Recomposition",cal:high?1650:1450,protein:185,carbs:high?140:90,fat:40,why:high?"Higher carbohydrate allowance for a longer or harder session.":"Low-volume Phase A target from the submitted nutrition architecture."};if(w<=22)return{phase:"Metabolic Pivot · Step 1",cal:1950,protein:185,carbs:190,fat:50,why:"Step calories upward before high-volume work expands."};if(w<=24)return{phase:"Metabolic Pivot · Step 2",cal:2250,protein:185,carbs:240,fat:60,why:"Second step before full performance fueling."};return{phase:"Performance Fueling",cal:high?4000:3400,protein:200,carbs:high?600:450,fat:88,why:high?"High-demand target emphasizing glycogen replacement.":"Baseline Phase B performance target."}}
function nutritionHtml(w,name){const n=nutritionForWeek(w,name);return '<div class="nutrition-hero"><small>'+n.phase.toUpperCase()+'</small><strong>≈ '+n.cal.toLocaleString()+' kcal</strong><p>'+n.why+'</p></div><div class="macro-grid"><div><span>Protein</span><strong>'+n.protein+' g</strong></div><div><span>Carbs</span><strong>'+n.carbs+' g</strong></div><div><span>Fat</span><strong>'+n.fat+' g</strong></div></div><div class="nutrition-note"><strong>Adaptive rule</strong><p>Readiness and body-weight trend override an aggressive deficit when recovery or performance deteriorates.</p></div>'}
function programWeekForDate(d){const a=new Date(programStart()),b=new Date(d);a.setHours(12,0,0,0);b.setHours(12,0,0,0);return Math.max(1,Math.min(56,Math.floor((b-a)/604800000)+1))}
function programDayIndex(d){const a=new Date(programStart()),b=new Date(d);a.setHours(12,0,0,0);b.setHours(12,0,0,0);const days=Math.floor((b-a)/86400000);return((days%7)+7)%7}
function dateSession(d){const w=programWeekForDate(d),bl=blockForWeek(w),name=daysFor(bl)[programDayIndex(d)];return{w,bl,name,det:makeSession(name)}}
function dateState(d){const k=dayKey(d),check=logs().some(x=>dayKey(x.date)===k),work=workouts().some(x=>dayKey(x.date)===k&&x.completed==="YES"),failed=JSON.parse(localStorage.failedDays||"[]").includes(k);return{check,work,failed}}
function openDaySheet(d,tab="training"){const x=dateSession(d);window.selectedDay=new Date(d);$("daySheetKicker").textContent="WEEK "+x.w+" · "+x.bl.name.toUpperCase();$("daySheetTitle").textContent=d.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});$("daySheet").classList.remove("hidden");document.querySelectorAll(".day-tab").forEach(b=>b.classList.toggle("active",b.dataset.daytab===tab));renderDaySheetTab(tab)}
function renderDaySheetTab(tab){const d=window.selectedDay||new Date(),x=dateSession(d),state=dateState(d);if(tab==="nutrition"){$("daySheetBody").innerHTML=nutritionHtml(x.w,x.name);return}$("daySheetBody").innerHTML='<div class="day-status-line"><span class="'+(state.check?"done":"")+'">'+(state.check?"✓":"○")+' Check-in</span><span class="'+(state.work?"done":"")+'">'+(state.work?"✓":"○")+' Training</span>'+(state.failed?'<span class="failed">× Missed</span>':'')+'</div><div class="day-training-hero"><small>'+x.det.type.toUpperCase()+'</small><h3>'+x.det.title+'</h3><p>'+x.det.why+'</p></div><div class="day-exercises">'+x.det.steps.map((e,i)=>'<button data-dayex="'+i+'"><b>'+(i+1)+'</b><div><strong>'+e.name+'</strong><small>'+e.dose+' · '+e.rest+'</small></div><span>›</span></button>').join("")+'</div>';$("daySheetBody").querySelectorAll("[data-dayex]").forEach(b=>b.onclick=()=>openExercise(x.det.steps[+b.dataset.dayex]))}
function renderMonth(){const base=new Date(viewedMonth.getFullYear(),viewedMonth.getMonth(),1,12),year=base.getFullYear(),month=base.getMonth();$("monthTitle").textContent=base.toLocaleDateString(undefined,{month:"long",year:"numeric"});const first=(base.getDay()+6)%7,last=new Date(year,month+1,0).getDate(),cells=[];for(let i=0;i<first;i++)cells.push('<div class="month-cell empty"></div>');for(let day=1;day<=last;day++){const d=new Date(year,month,day,12),afterStart=!localStorage.programStart||d>=new Date(programStart()),w=programWeekForDate(d),macro=macroForWeek(w),state=dateState(d),today=d.toDateString()===new Date().toDateString(),future=d>new Date();cells.push('<button class="month-cell '+(today?"today ":"")+(state.check&&state.work?"complete ":"")+(state.failed?"failed ":"")+(future?"future ":"")+'" data-date="'+d.toISOString()+'" '+(!afterStart?"disabled":"")+'><span>'+day+'</span><i style="background:'+phasePalette[macro.name]+'"></i></button>')} $("monthGrid").innerHTML=cells.join("");$("monthLegend").innerHTML=macroPhases.map(x=>'<span><i style="background:'+phasePalette[x[0]]+'"></i>'+x[0]+'</span>').join("");$("monthGrid").querySelectorAll("[data-date]").forEach(b=>b.onclick=()=>openDaySheet(new Date(b.dataset.date)))}
function renderWeek(){const w=viewedWeek,bl=blockForWeek(w),days=daysFor(bl),st=dateFor(w,0),en=dateFor(w,6);$("weekTitle").textContent="Week "+w;$("weekRange").textContent=st.toLocaleDateString(undefined,{month:"short",day:"numeric"})+" – "+en.toLocaleDateString(undefined,{month:"short",day:"numeric"});$("weekSummary").innerHTML='<div class="week-card"><div class="week-overview"><small>'+bl.name.toUpperCase()+'</small><strong>'+bl.focus+'</strong><p>'+bl.run+' · '+bl.ruck+'</p></div>'+days.map((name,i)=>{const det=makeSession(name),date=dateFor(w,i),is=date.toDateString()===todayKey(),state=dateState(date);return'<div class="day-row '+(state.check&&state.work?"done ":"")+(state.failed?"failed ":"")+(is?"today-row":"")+'"><button class="day-button" data-i="'+i+'"><div class="day-date"><strong>'+date.toLocaleDateString(undefined,{weekday:"short"})+'</strong><small>'+date.getDate()+'</small></div><span class="day-state">'+(state.failed?"×":state.check&&state.work?"✓":"○")+'</span><div class="day-desc"><strong>'+det.title+'</strong><small>'+det.type+' · '+det.effort+'</small></div><span class="day-chevron">›</span></button></div>'}).join("")+'</div>';$("weekSummary").querySelectorAll(".day-button").forEach(btn=>btn.onclick=()=>openDaySheet(dateFor(w,+btn.dataset.i)))}
function phaseComplete(bl){const hs=workouts().filter(x=>x.week>=bl.start&&x.week<=bl.end&&x.completed==="YES"),total=(bl.end-bl.start+1)*7,done=new Set(hs.map(x=>new Date(x.date).toDateString())).size;return{done,total,pct:Math.min(100,Math.round(done/total*100))}}
const macroPhases=[["Rebuild",1,12,"Recondition, build aerobic base and restore tissue tolerance."],["Build",13,24,"Increase running, weighted-pack walking and controlled faster work."],["Specificity",25,40,"Shift toward running, loaded movement, bodyweight strength and consecutive-day durability."],["Work Capacity",41,52,"Build high accumulated workload and prolonged time on feet."],["Taper",53,56,"Dissipate fatigue while retaining selected intensity."]];
const phaseObjectives=[
 {name:"Establish the system",goal:s=>s.checkins>=7,progress:s=>Math.min(1,s.checkins/7),label:s=>s.checkins+"/7 check-ins"},
 {name:"Build strength consistency",goal:s=>s.strength>=4,progress:s=>Math.min(1,s.strength/4),label:s=>s.strength+"/4 strength sessions"},
 {name:"Build the engine",goal:s=>s.aerobic>=4,progress:s=>Math.min(1,s.aerobic/4),label:s=>s.aerobic+"/4 aerobic sessions"},
 {name:"Stack two complete weeks",goal:s=>s.completeDays>=14,progress:s=>Math.min(1,s.completeDays/14),label:s=>s.completeDays+"/14 complete days"},
 {name:"Twenty-one day discipline",goal:s=>s.checkins>=21,progress:s=>Math.min(1,s.checkins/21),label:s=>s.checkins+"/21 check-ins"},
 {name:"Strength base II",goal:s=>s.strength>=8,progress:s=>Math.min(1,s.strength/8),label:s=>s.strength+"/8 strength sessions"},
 {name:"Aerobic base II",goal:s=>s.aerobic>=8,progress:s=>Math.min(1,s.aerobic/8),label:s=>s.aerobic+"/8 aerobic sessions"},
 {name:"Four complete weeks",goal:s=>s.completeDays>=28,progress:s=>Math.min(1,s.completeDays/28),label:s=>s.completeDays+"/28 complete days"},
 {name:"Forty check-ins",goal:s=>s.checkins>=40,progress:s=>Math.min(1,s.checkins/40),label:s=>s.checkins+"/40 check-ins"},
 {name:"Twelve strength sessions",goal:s=>s.strength>=12,progress:s=>Math.min(1,s.strength/12),label:s=>s.strength+"/12 strength sessions"},
 {name:"Twelve engine sessions",goal:s=>s.aerobic>=12,progress:s=>Math.min(1,s.aerobic/12),label:s=>s.aerobic+"/12 aerobic sessions"},
 {name:"Phase finisher",goal:s=>s.mastery>=.9,progress:s=>Math.min(1,s.mastery/.9),label:s=>Math.round(s.mastery*100)+"% mastery"}
];
function macroForWeek(w){const x=macroPhases.find(p=>w>=p[1]&&w<=p[2])||macroPhases[0];return{name:x[0],start:x[1],end:x[2],focus:x[3]}}
function macroStats(p){const ls=logs().filter(x=>x.week>=p.start&&x.week<=p.end),ws=workouts().filter(x=>x.week>=p.start&&x.week<=p.end&&x.completed==="YES"),failed=JSON.parse(localStorage.failedDays||"[]").filter(k=>{const w=programWeekForDate(new Date(k));return w>=p.start&&w<=p.end}).length,checkKeys=new Set(ls.map(x=>dayKey(x.date))),completeKeys=new Set(ws.filter(w=>checkKeys.has(dayKey(w.date))).map(x=>dayKey(x.date))),total=(p.end-p.start+1)*7;return{checkins:checkKeys.size,strength:ws.filter(x=>/strength|carry/i.test(x.session||"")).length,aerobic:ws.filter(x=>/run|row|aerobic|recovery/i.test(x.session||"")).length,completeDays:completeKeys.size,failed,total,mastery:Math.max(0,(completeKeys.size-failed*.5)/total)}}
function renderProgram(){const cur=macroForWeek(currentWeek()),stats=macroStats(cur),completed=phaseObjectives.filter(o=>o.goal(stats)).length,tier=Math.min(Math.floor(completed/4),2),shown=phaseObjectives.slice(tier*4,tier*4+4),pc=Math.round(stats.mastery*100);$("currentPhaseCard").innerHTML='<div class="phase-feature-top"><div><small>PHASE '+(macroPhases.findIndex(x=>x[0]===cur.name)+1)+' OF '+macroPhases.length+'</small><h2>'+cur.name+'</h2><p>Weeks '+cur.start+'–'+cur.end+'<br>'+cur.focus+'</p></div><div class="xp-chip">LEVEL '+(tier+1)+'</div></div><div class="phase-progress-box"><div class="phase-ring" style="--p:'+pc+'"><span>'+pc+'%</span></div><div class="phase-progress-copy"><strong>'+stats.completeDays+' complete days</strong><small>'+stats.failed+' failed · '+missedDays().length+' unresolved</small><div class="progress-bar"><i style="width:'+pc+'%"></i></div></div></div>';$("objectiveMeta").innerHTML='<strong>Objective Set '+(tier+1)+'</strong><span>Complete all four to unlock the next set.</span>';$("milestoneCount").textContent=completed+"/"+phaseObjectives.length;$("phaseMilestones").innerHTML=shown.map((o,i)=>{const done=o.goal(stats),pct=Math.round(o.progress(stats)*100);return'<div class="milestone quest '+(done?"done":"")+'"><span class="milestone-state">'+(done?"✓":tier*4+i+1)+'</span><div><strong>'+o.name+'</strong><small>'+o.label(stats)+'</small><div class="quest-progress"><i style="width:'+pct+'%"></i></div></div><b>'+(done?"+100 XP":pct+"%")+'</b></div>'}).join("");$("programBlocks").innerHTML=macroPhases.map((x,i)=>{const p={name:x[0],start:x[1],end:x[2],focus:x[3]},st=macroStats(p),pct=Math.round(st.mastery*100),active=cur.name===p.name;return'<div class="phase-card '+(active?"current":"")+'"><span class="phase-num">'+(i+1)+'</span><div><strong>'+p.name+'</strong><small>Weeks '+p.start+'–'+p.end+'</small></div><span class="phase-pct">'+pct+'%</span></div>'}).join("")}
function draw(id,a){const c=$(id),ctx=c.getContext("2d"),w=c.clientWidth||320,h=160,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;ctx.scale(d,d);ctx.clearRect(0,0,w,h);if(a.length<2){ctx.fillStyle="#8fa8bd";ctx.font="12px -apple-system, BlinkMacSystemFont, sans-serif";ctx.fillText("Save more check-ins to build this trend.",10,80);return}const mn=Math.min(...a),mx=Math.max(...a),sp=mx-mn||1,p=12;ctx.strokeStyle="#1794ff";ctx.lineWidth=2.5;ctx.beginPath();a.forEach((v,i)=>{const x=p+i*(w-2*p)/(a.length-1),y=h-p-(v-mn)*(h-2*p)/sp;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function renderTrends(){const l=logs().slice(0,28).reverse(),map={RED:30,YELLOW:65,GREEN:90},wt=l.filter(x=>Number.isFinite(x.weight)).map(x=>x.weight);$("trendRecovery").textContent=l.length?l.length+" check-ins":"No data";$("trendWeight").textContent=wt.length?wt.at(-1).toFixed(1)+" lb":"No data";requestAnimationFrame(()=>{draw("recoveryChart",l.map(x=>x.score||map[x.overall]||50));draw("weightChart",wt)});const a=[...logs().map(x=>({...x,k:"Check-in"})),...workouts().map(x=>({...x,k:"Session"}))].sort((x,y)=>new Date(y.date)-new Date(x.date)).slice(0,8);$("trendLogList").innerHTML=a.length?a.map(x=>'<div class="log-card"><div><strong>'+(x.k==="Session"?x.session:"Morning check-in")+'</strong><small>'+new Date(x.date).toLocaleDateString()+' · Week '+x.week+'</small></div><small>'+(x.k==="Session"?(x.completed||""):(x.overall||""))+'</small></div>').join(""):'<div class="log-card"><small>No activity saved yet.</small></div>';countRecords()}
function openCheckin(){$("checkinSheet").classList.remove("hidden");requiredFields();bindInfo($("checkinSheet"))}function closeCheckin(){$("checkinSheet").classList.add("hidden")}function closeModal(){$("infoModal").classList.add("hidden")}function bindInfo(root){(root||document).querySelectorAll(".info-dot[data-term]").forEach(b=>b.onclick=e=>{e.stopPropagation();openInfo(b.dataset.term)})}
function switchTab(t){$("headerAction").style.display=t==="today"?"grid":"none";document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(t).classList.add("active");document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.target===t));$("pageTitle").textContent=t==="workout"?"Train":t.charAt(0).toUpperCase()+t.slice(1);$("todayDate").textContent=t==="today"?new Date().toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"}):"";window.scrollTo({top:0,left:0,behavior:"instant"});if(t==="workout")renderTrain();if(t==="week")renderWeek();if(t==="trends")renderTrends();if(t==="program")renderProgram()}
function renderAll(){applyBaselines();renderMissedBanner();renderToday();renderTrain();renderWeek();renderTrends();renderProgram();requiredFields();bindInfo(document)}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>switchTab(b.dataset.target));$("headerAction").onclick=()=>switchTab("week");$("taskCheckin").onclick=openCheckin;$("todayWorkoutCard").onclick=()=>switchTab("workout");$("taskWorkout").onclick=()=>switchTab("workout");$("taskNutrition").onclick=()=>openDaySheet(new Date(),"nutrition");$("taskMobility").onclick=()=>{setTask("mobility",!taskDone("mobility"));renderToday()};$("closeCheckin").onclick=closeCheckin;$("checkinSheet").onclick=e=>{if(e.target===$("checkinSheet"))closeCheckin()};$("evaluateBtn").onclick=evaluate;$("saveBtn").onclick=saveCheckin;$("completeWorkoutQuick").onclick=()=>saveWorkout("YES");$("completeWorkout").onclick=()=>saveWorkout(val("completed")||"YES");$("modalClose").onclick=closeModal;$("modalDone").onclick=closeModal;$("infoModal").onclick=e=>{if(e.target===$("infoModal"))closeModal()};document.querySelectorAll(".calendar-mode-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".calendar-mode-btn").forEach(x=>x.classList.toggle("active",x===b));$("weekView").classList.toggle("hidden",b.dataset.calview!=="week");$("monthView").classList.toggle("hidden",b.dataset.calview!=="month");if(b.dataset.calview==="month")renderMonth()});$("prevMonth").onclick=()=>{viewedMonth=new Date(viewedMonth.getFullYear(),viewedMonth.getMonth()-1,1);renderMonth()};$("nextMonth").onclick=()=>{viewedMonth=new Date(viewedMonth.getFullYear(),viewedMonth.getMonth()+1,1);renderMonth()};$("daySheetClose").onclick=()=>$("daySheet").classList.add("hidden");$("daySheet").onclick=e=>{if(e.target===$("daySheet"))$("daySheet").classList.add("hidden")};document.querySelectorAll(".day-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".day-tab").forEach(x=>x.classList.toggle("active",x===b));renderDaySheetTab(b.dataset.daytab)});$("prevWeek").onclick=()=>{viewedWeek=Math.max(1,viewedWeek-1);renderWeek()};$("nextWeek").onclick=()=>{viewedWeek=Math.min(56,viewedWeek+1);renderWeek()};if($("librarySearch"))$("librarySearch").addEventListener("input",e=>renderLibrary(e.target.value));document.querySelectorAll(".segment").forEach(b=>b.onclick=()=>{document.querySelectorAll(".segment").forEach(x=>x.classList.toggle("active",x===b));$("trainSessionView").classList.toggle("hidden",b.dataset.trainview!=="session");$("trainLibraryView").classList.toggle("hidden",b.dataset.trainview!=="library")});
["hrv","hrvBase","rhr","rhrBase","sleep","sleepQ","fatigue","grip","gripBase","load","pain","performance","weight","weightAvg"].forEach(id=>{const v=localStorage.getItem("input_"+id);if(v!==null)$(id).value=v;$(id).addEventListener("input",requiredFields);$(id).addEventListener("change",requiredFields)});$("focal").checked=localStorage.input_focal==="1";$("gait").checked=localStorage.input_gait==="1";
const DB_NAME="AdaptiveLandPrepDB",STORE="kv";function openDB(){return new Promise((r,j)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}async function dbSet(k,v){try{const d=await openDB();d.transaction(STORE,"readwrite").objectStore(STORE).put(v,k)}catch(e){}}async function requestPersistence(){let p=false;try{p=await navigator.storage?.persisted?.()||await navigator.storage?.persist?.()}catch(e){}$("persistBadge").textContent=p?"Persistent":"On device";$("dbStatus").textContent=p?"Persistent storage granted":"Local database active; keep periodic backups"}function countRecords(){$("recordCount").textContent=(logs().length+workouts().length)+" records";$("lastBackup").textContent=localStorage.lastBackupAt?new Date(localStorage.lastBackupAt).toLocaleString():"Never"}function exportBackup(){const p={app:"Adaptive Land Prep",formatVersion:2,exportedAt:new Date().toISOString(),data:{trainingLogs:localStorage.trainingLogs||"[]",workoutHistory:localStorage.workoutHistory||"[]",programStart:localStorage.programStart}},b=new Blob([JSON.stringify(p,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="adaptive-land-prep-backup.json";a.click();localStorage.lastBackupAt=p.exportedAt;countRecords()}async function importBackup(f){const o=JSON.parse(await f.text());if(o.app!=="Adaptive Land Prep")throw Error();Object.entries(o.data).forEach(x=>localStorage.setItem(x[0],x[1]));location.reload()}$("exportBackup").onclick=exportBackup;$("importBackup").onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]).catch(()=>alert("That backup could not be restored."));
$("headerAction").innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="5.5" width="16" height="14" rx="2.5"/><path d="M8 3.5v4M16 3.5v4M4 9.5h16"/></svg>';$("headerAction").style.display="grid";renderAll();requestPersistence();if("serviceWorker"in navigator)addEventListener("load",async()=>{const r=await navigator.serviceWorker.register("./service-worker.js");r.update();navigator.serviceWorker.addEventListener("controllerchange",()=>{if(!sessionStorage.swReloaded){sessionStorage.swReloaded="1";location.reload()}})});
