const $=id=>document.getElementById(id),n=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:null},s=id=>$(id)?.value||"";
const blocks=[["Re-entry",1,4,"Run/walk 0–2 exposures; C2 2–3×40–60 min","None","Recondition and establish baselines"],["Foundation I",5,8,"2 runs/week; ~3–6 mi","2–4 mi easy","Continuous running tolerance"],["Foundation II",9,12,"2–3 runs/week; ~6–10 mi","3–5 mi easy","Aerobic base and calisthenics"],["Build I",13,16,"3 runs/week; ~10–16 mi","4–6 mi","Controlled threshold introduction"],["Build II",17,20,"3 runs/week; ~14–20 mi","5–8 mi","Long-run growth"],["Build III",21,24,"3 runs/week; ~16–22 mi","6–10 mi","Consolidate and test"],["Specificity I",25,28,"3–4 runs/week; ~20–26 mi","8–10 mi","Running economy and ruck technique"],["Specificity II",29,32,"3–4 runs/week; ~22–30 mi","8–12 mi","Threshold + long aerobic"],["Specificity III",33,36,"4 runs/week; ~26–34 mi","10–14 mi","Consecutive-day exposure"],["Specificity IV",37,40,"3–4 runs/week; ~24–32 mi","10–14 mi","Absorb training"],["Work Capacity I",41,44,"4 runs/week; ~28–38 mi","12–16 mi","Accumulated workload"],["Work Capacity II",45,48,"4–5 runs/week; ~34–45 mi","14–20 mi","Peak specificity"],["Peak / Consolidate",49,52,"~38–50 mi only if earned","16–24 mi only if earned","Peak work-capacity assessment"],["Taper",53,56,"Reduce 30→80%","Reduce then eliminate","Dissipate fatigue"]];
const templates={Re:["Recovery + mobility","Strength A","Concept2 Z2","Strength B","Concept2 Z2","Run/walk exposure","Easy C2 + core"],Fo:["Recovery","Strength + calisthenics","Concept2 Z2","Easy run + lower leg","Strength B","Long easy run / ruck","Easy C2"],Bu:["Recovery","Quality aerobic + strength","Easy run","Concept2 / threshold","Strength + calisthenics","Long run / ruck","Easy C2"],Sp:["Recovery","Quality run + calisthenics","Easy run","Strength + C2","Easy run + carries","Long ruck / run","Recovery aerobic"],Wo:["Recovery","Quality run","Medium run","Strength + carries","Easy run","Long ruck/run","Fatigued easy aerobic"],Pe:["Recovery","Quality / specific work","Medium run","Carries + strength","Easy run","Peak specific session","Recovery"],Ta:["Recovery","Short quality","Easy aerobic","Light strength","Easy aerobic","Short specific session","Recovery"]};
function currentWeek(){return Math.max(1,Math.min(56,parseInt(localStorage.programWeek||1)))}
function blockForWeek(w){const x=blocks.find(b=>w>=b[1]&&w<=b[2])||blocks[0];return{phase:x[0],start:x[1],end:x[2],run:x[3],ruck:x[4],focus:x[5]}}
function daysFor(p){const k=p.startsWith("Re")?"Re":p.startsWith("Fo")?"Fo":p.startsWith("Bu")?"Bu":p.startsWith("Sp")?"Sp":p.startsWith("Wo")?"Wo":p.startsWith("Pe")?"Pe":"Ta";return templates[k]}
function systemic(){const sleep=n("sleep"),sq=n("sleepQ"),fat=n("fatigue"),h=n("hrv"),hb=n("hrvBase"),r=n("rhr"),rb=n("rhrBase"),g=n("grip"),gb=n("gripBase"),perf=s("performance");if([sleep,sq,fat,h,r].every(v=>v===null)&&!perf)return"";if((sleep!==null&&sleep<6)||(sq!==null&&sq<=2)||(fat!==null&&fat>=4)||(hb&&h!==null&&h<.85*hb)||(rb&&r!==null&&r>rb+8)||perf==="NO")return"RED";if((sleep!==null&&sleep<7)||sq===3||fat===3||(hb&&h!==null&&h<.92*hb)||(rb&&r!==null&&r>rb+5)||(gb&&g!==null&&g<.9*gb))return"YELLOW";return"GREEN"}
function mechanical(){const p=n("pain");if(p===null&&!$("focal").checked&&!$("gait").checked)return"";if($("focal").checked||$("gait").checked||(p!==null&&p>=5))return"RED";if(p!==null&&p>=3)return"YELLOW";return"GREEN"}
function fueling(){const w=n("weight"),a=n("weightAvg"),l=n("load");if(w===null||a===null||l===null)return"";if(w<a*.985&&l>=7)return"RED";if(w<a*.99&&l>=5)return"YELLOW";return"GREEN"}
function overall(a,b,c){if(!a&&!b&&!c)return"";if(a==="RED"||b==="RED")return"RED";if(a==="YELLOW"||b==="YELLOW"||c==="RED")return"YELLOW";return"GREEN"}
function color(el,v){if(!el)return;el.textContent=v||"—";el.style.color=v==="GREEN"?"var(--green)":v==="YELLOW"?"var(--yellow)":v==="RED"?"var(--red)":"var(--muted)"}
function persistInputs(){["hrv","hrvBase","rhr","rhrBase","sleep","sleepQ","fatigue","grip","gripBase","load","pain","performance","weight","weightAvg"].forEach(id=>localStorage.setItem("input_"+id,$(id).value));localStorage.input_focal=$("focal").checked?"1":"0";localStorage.input_gait=$("gait").checked?"1":"0"}
function evaluate(){const a=systemic(),b=mechanical(),c=fueling(),o=overall(a,b,c);color($("sysStatus"),a);color($("mechStatus"),b);color($("fuelStatus"),c);color($("overallStatus"),o);$("statusPill").textContent=o||"—";$("statusPill").className="status-pill "+(o?o.toLowerCase():"neutral");let run,ruck,c2,strength,intensity,nutrition,warn="";if(!o)run=ruck=c2=strength=intensity=nutrition="Complete inputs";else{run=b==="RED"?"NO RUN":o==="RED"?"C2 / WALK ONLY":o==="YELLOW"?"Reduce 25–40%; easy":"Full phase plan";ruck=b==="RED"?"NO RUCK":o==="RED"?"No loaded ruck":o==="YELLOW"?"Reduce / light":"Full phase plan";c2=b==="RED"?"Easy C2 if pain-free":o==="RED"?"Recovery C2":o==="YELLOW"?"Prefer easy C2":"Phase plan";strength=b==="RED"?"Non-aggravating only":a==="RED"?"Cut ~50%":o==="YELLOW"?"Cut ~30%":"Full plan";intensity=o==="GREEN"?"Planned":o==="YELLOW"?"Easy only / no hard intervals":"No hard training";nutrition=c==="RED"?"Add energy/carbs; review deficit":c==="YELLOW"?"Hold / add carbs around training":"Follow phase target";if(b==="RED")warn="Mechanical override: do not let favorable HRV justify impact or load carriage.";else if(a==="RED")warn="Systemic recovery flag: reduce stress and reassess."}for(const [id,v] of [["runDecision",run],["ruckDecision",ruck],["c2Decision",c2],["strengthDecision",strength],["intensityDecision",intensity],["nutritionDecision",nutrition]])$(id).textContent=v;$("warningBox").textContent=warn;$("warningBox").classList.toggle("hidden",!warn);$("results").classList.remove("hidden");persistInputs();return{sys:a,mech:b,fuel:c,ov:o,run,ruck,c2}}
function saveLog(){const r=evaluate();if(!r.ov)return;const logs=JSON.parse(localStorage.trainingLogs||"[]");logs.unshift({date:new Date().toISOString(),week:currentWeek(),weight:n("weight"),hrv:n("hrv"),rhr:n("rhr"),sleep:n("sleep"),overall:r.ov,run:r.run,ruck:r.ruck,c2:r.c2});localStorage.trainingLogs=JSON.stringify(logs.slice(0,180));dbSet("trainingLogs",localStorage.trainingLogs);updateDashboard();updateCalibration();renderTrends();$("saveBtn").textContent="Saved ✓";setTimeout(()=>$("saveBtn").textContent="Save Today to Log",1200)}
function renderWeek(){const w=Math.max(1,Math.min(56,parseInt($("weekInput").value||1)));localStorage.programWeek=w;dbSet("programWeek",String(w));const b=blockForWeek(w),days=daysFor(b.phase);$("heroPhase").textContent=`Week ${w} · ${b.phase}`;$("weekSummary").innerHTML=`<div class="week-card"><h3>Week ${w} · ${b.phase}</h3><div class="meta">${w>=53?"TAPER":w%4===0?"CONSOLIDATE WEEK":"BUILD WEEK"}</div><div class="kv"><span>Running</span><strong>${b.run}</strong><span>Ruck</span><strong>${b.ruck}</strong><span>Focus</span><strong>${b.focus}</strong></div><div class="day-list">${["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((d,i)=>`<div class="day"><b>${d}</b><div>${days[i]}</div></div>`).join("")}</div></div>`;updateDashboard()}
function renderProgram(){$("programBlocks").innerHTML=blocks.map(x=>`<div class="block-card"><div class="range">WEEKS ${x[1]}–${x[2]}</div><h3>${x[0]}</h3><p>${x[5]}</p><div class="kv"><span>Run</span><strong>${x[3]}</strong><span>Ruck</span><strong>${x[4]}</strong></div></div>`).join("")}
function updateDashboard(){const w=currentWeek(),b=blockForWeek(w),logs=JSON.parse(localStorage.trainingLogs||"[]");$("dashWeek").textContent=w;$("dashPhase").textContent=b.phase;$("dashFocus").textContent=b.focus;$("weekProgress").style.width=(w/56*100)+"%";$("dashRecovery").textContent=logs[0]?.overall||"—"}
function updateCalibration(){const c=Math.min(7,JSON.parse(localStorage.trainingLogs||"[]").length);$("calCount").textContent=c;$("calibrationTitle").textContent=c>=7?"Baseline established":"Baseline calibration";$("calibrationText").textContent=c>=7?"Adaptive decisions now have useful personal history.":`${7-c} more check-in${7-c===1?"":"s"} to establish an initial trend.`}
function todaySession(){const b=blockForWeek(currentWeek()),i=(new Date().getDay()+6)%7;return{b,name:daysFor(b.phase)[i]}}
function renderWorkout(){const x=todaySession(),logs=JSON.parse(localStorage.trainingLogs||"[]"),last=logs[0];let mod="FULL",cls="",exp="Follow the scheduled prescription.";if(last&&new Date(last.date).toDateString()===new Date().toDateString()){if(last.overall==="RED"){mod="RECOVERY";cls="stop";exp="Today’s check-in calls for recovery-level work."}else if(last.overall==="YELLOW"){mod="MODIFIED";cls="reduce";exp="Reduce mechanical load/intensity roughly 25–40%."}}$("workoutKicker").textContent=`TODAY · WEEK ${currentWeek()} · ${x.b.phase.toUpperCase()}`;$("workoutTitle").textContent=x.name;$("workoutPrescription").innerHTML=`<div class="rx-card"><div class="rx-top"><div><div class="rx-type">TODAY'S SESSION</div><h3>${x.name}</h3></div><div class="rx-badge ${cls}">${mod}</div></div><p>Complete the scheduled work at controlled effort. Mechanical health takes priority over favorable recovery metrics.</p></div><div class="insight-copy"><strong>Adaptive instruction:</strong> ${exp}<br><br><strong>Phase focus:</strong> ${x.b.focus}</div>`}
function completeWorkout(){const comp=s("completed");if(!comp){alert("Choose whether the session was completed.");return}const x=todaySession(),arr=JSON.parse(localStorage.workoutHistory||"[]"),rpe=n("sessionRPE"),dur=n("sessionDuration");arr.unshift({date:new Date().toISOString(),week:currentWeek(),session:x.name,rpe,duration:dur,postPain:n("postPain"),completed:comp,note:s("sessionNote")});localStorage.workoutHistory=JSON.stringify(arr.slice(0,365));dbSet("workoutHistory",localStorage.workoutHistory);if(rpe!==null&&dur!==null){const l=Math.min(10,Math.round(rpe*dur/60));localStorage.input_load=l;$("load").value=l}$("completionBanner").classList.remove("hidden");setTimeout(()=>$("completionBanner").classList.add("hidden"),2000);renderTrends()}
function draw(id,vals){const c=$(id),ctx=c.getContext("2d"),w=c.clientWidth,h=150,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;ctx.scale(d,d);if(vals.length<2){ctx.fillStyle="#a9bad0";ctx.font="13px -apple-system";ctx.fillText("Save check-ins to build this trend.",8,75);return}const mn=Math.min(...vals),mx=Math.max(...vals),sp=mx-mn||1;ctx.strokeStyle="#4da3ff";ctx.lineWidth=2.5;ctx.beginPath();vals.forEach((v,i)=>{const x=10+i*(w-20)/(vals.length-1),y=h-10-(v-mn)*(h-20)/sp;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function renderTrends(){const logs=JSON.parse(localStorage.trainingLogs||"[]").slice(0,28).reverse(),map={RED:0,YELLOW:1,GREEN:2},wv=logs.filter(x=>x.weight!=null).map(x=>x.weight);$("trendRecovery").textContent=logs.length?`${logs.length} check-ins`:"No data";$("trendWeight").textContent=wv.length?`${wv.at(-1).toFixed(1)} lb`:"No data";requestAnimationFrame(()=>{draw("recoveryChart",logs.map(x=>map[x.overall]));draw("weightChart",wv)});$("trendLogList").innerHTML=logs.slice(-5).reverse().map(x=>`<div class="log-card"><strong>Week ${x.week} · ${x.overall}</strong><div class="hero-sub">${new Date(x.date).toLocaleDateString()}</div></div>`).join("")||'<div class="week-card"><p class="hero-sub">No saved check-ins yet.</p></div>';countRecords()}
const DB_NAME="AdaptiveLandPrepDB",STORE="kv";function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function dbSet(k,v){try{const d=await openDB(),t=d.transaction(STORE,"readwrite");t.objectStore(STORE).put(v,k)}catch(e){}}async function requestPersistence(){let p=false;try{p=await navigator.storage?.persisted?.()||await navigator.storage?.persist?.()}catch(e){}$("persistBadge").textContent=p?"PERSISTENT":"ON DEVICE";$("persistBadge").classList.toggle("good",p);$("dbStatus").textContent=p?"Persistent storage granted":"IndexedDB active; periodic backup recommended"}
function countRecords(){const a=JSON.parse(localStorage.trainingLogs||"[]").length,b=JSON.parse(localStorage.workoutHistory||"[]").length;$("recordCount").textContent=`${a+b} records`;$("lastBackup").textContent=localStorage.lastBackupAt?new Date(localStorage.lastBackupAt).toLocaleString():"Never"}
function exportBackup(){const payload={app:"Adaptive Land Prep",formatVersion:1,exportedAt:new Date().toISOString(),data:{trainingLogs:localStorage.trainingLogs||"[]",workoutHistory:localStorage.workoutHistory||"[]",programWeek:String(currentWeek())}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="adaptive-land-prep-backup.json";a.click();localStorage.lastBackupAt=payload.exportedAt;countRecords()}
async function importBackup(f){const o=JSON.parse(await f.text());if(o.app!=="Adaptive Land Prep")throw Error();Object.entries(o.data).forEach(([k,v])=>localStorage.setItem(k,v));location.reload()}
document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));btn.classList.add("active");document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(btn.dataset.target).classList.add("active");$("pageTitle").textContent=btn.querySelector("small").textContent;if(btn.dataset.target==="workout")renderWorkout();if(btn.dataset.target==="week")renderWeek();if(btn.dataset.target==="trends")renderTrends()}));
$("evaluateBtn").onclick=evaluate;$("saveBtn").onclick=saveLog;$("completeWorkout").onclick=completeWorkout;$("weekInput").onchange=renderWeek;$("exportBackup").onclick=exportBackup;$("importBackup").onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]).catch(()=>alert("That backup could not be restored."));
["hrv","hrvBase","rhr","rhrBase","sleep","sleepQ","fatigue","grip","gripBase","load","pain","performance","weight","weightAvg"].forEach(id=>{const v=localStorage.getItem("input_"+id);if(v!==null)$(id).value=v});$("focal").checked=localStorage.input_focal==="1";$("gait").checked=localStorage.input_gait==="1";$("weekInput").value=currentWeek();renderWeek();renderProgram();renderWorkout();renderTrends();updateCalibration();requestPersistence();if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js"));