const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const app=fs.readFileSync('app.js','utf8'),training=fs.readFileSync('training-tools.js','utf8');
function harness(){const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};const ctx=vm.createContext({localStorage:storage,dayKey:d=>new Date(d).toDateString(),dayDate:()=>new Date('2026-09-08T12:00:00Z'),todayWorkoutRecord:()=>null,workouts:()=>[]});vm.runInContext(training,ctx);return{ctx,storage,map}}
test('breakfast precedes training and recording it reveals training without completing nutrition',()=>{let eaten=false,trained=false,complete=false;const ctx=vm.createContext({localStorage:{programStart:'2026-09-08'},daySession:()=>({closedAt:null}),todayCheckin:()=>({}),todayWorkoutRecord:()=>trained,todayMealPlan:()=>[{id:'breakfast'}],getNutritionLog:()=>({meals:eaten?['breakfast']:[]}),nutritionDayComplete:()=>complete});vm.runInContext(app.slice(app.indexOf('function todayFlowState(){'),app.indexOf('function directiveTimeline(')),ctx);assert.equal(ctx.todayFlowState(),'breakfast');eaten=true;assert.equal(ctx.todayFlowState(),'directive');trained=true;assert.equal(ctx.todayFlowState(),'nutrition');complete=true;assert.equal(ctx.todayFlowState(),'evening')});
test('set entries persist, retain measurement units and reject invalid input before writing',()=>{const h=harness(),row={name:'Squat',unit:'lb',load:40,measure:'reps',work:8};h.ctx.saveExerciseSets([row]);assert.equal(h.ctx.recordedExerciseSets()[0].load,40);assert.throws(()=>h.ctx.saveExerciseSets([{...row,load:-1}]));assert.equal(h.ctx.recordedExerciseSets()[0].load,40);assert.throws(()=>h.ctx.saveExerciseSets([{...row,work:Infinity}]));});
test('previous sets exclude today, skipped sessions and other movements',()=>{const h=harness(),row={name:'Squat',unit:'kg',load:30,measure:'reps',work:8};h.ctx.workouts=()=>[{date:'2026-09-05T12:00:00Z',completed:'YES'},{date:'2026-09-07T12:00:00Z',completed:'YES',exerciseSets:[row]},{date:'2026-09-06T12:00:00Z',completed:'NO',exerciseSets:[row]},{date:'2026-09-08T12:00:00Z',completed:'YES',exerciseSets:[row]}];assert.equal(h.ctx.priorExerciseSets('Squat').length,1);assert.equal(h.ctx.priorExerciseSets('Curl').length,0)});
test('aerobic guidance distinguishes steady work and measured modality-specific targets',()=>{const h=harness(),e={type:'Row',name:'Easy row',cue:'Easy'};assert.match(h.ctx.aerobicGuidance(e),/not intervals/);assert.match(h.ctx.aerobicGuidance(e),/No measured/);h.storage.input_rowEasyLow='120';h.storage.input_rowEasyHigh='140';assert.match(h.ctx.aerobicGuidance(e),/120–140 bpm/);assert.match(h.ctx.aerobicGuidance({type:'Run',name:'Easy run'}),/No measured run/)});
test('No workout is neutral rather than failed performance',()=>{const ctx=vm.createContext({});vm.runInContext(app.slice(app.indexOf('function systemicDomainsFromRecord('),app.indexOf('function recentSystemicRecords(')),ctx);assert.equal(ctx.systemicDomainsFromRecord({performance:'NA'},false).performance,undefined)});

test('grip baseline converts explicit units and excludes unlabelled legacy values',()=>{
 const fields={gripUnit:{value:'kg'},hrvBase:{},rhrBase:{},gripBase:{},weightAvg:{}};
 const ctx=vm.createContext({$:id=>fields[id],val:id=>fields[id].value,historicalDate:null,logs:()=>[{date:'2026-09-07',grip:100,gripUnit:'lb'},{date:'2026-09-06',grip:50,gripUnit:'kg'},{date:'2026-09-05',grip:999}]});
 vm.runInContext(app.slice(app.indexOf('function avg('),app.indexOf('function persistInputs(')),ctx);ctx.applyBaselines();assert.equal(fields.gripBase.value,'47.7');fields.gripUnit.value='lb';ctx.applyBaselines();assert.equal(fields.gripBase.value,'105.1');
});
